/**
 * work-queue-management
 * Services to support Work Queue Management
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface MetadataVO {
  metadata1?: string;
  metadata2?: string;
  metadata3?: string;
  metadata4?: string;
  metadata5?: string;
  metadata6?: string;
  metadata7?: string;
  metadata8?: string;
  metadata9?: string;
  metadata10?: string;
  metadata11?: string;
  metadata12?: string;
  metadata13?: string;
  metadata14?: string;
  metadata15?: string;
  metadata16?: string;
  metadata17?: string;
  metadata18?: string;
  metadata19?: string;
  metadata20?: string;
  metadata21?: string;
  metadata22?: string;
  metadata23?: string;
  metadata24?: string;
  metadata25?: string;
  metadata26?: string;
  metadata27?: string;
  metadata29?: string;
  metadata30?: string;
  metadata31?: string;
  metadata32?: string;
  metadata33?: string;
  metadata34?: string;
  metadata35?: string;
  metadata36?: string;
  metadata37?: string;
  metadata38?: string;
  metadata39?: string;
  metadata40?: string;
  metadata41?: string;
  metadata42?: string;
}
