/**
 * work-queue-management
 * Services to support Work Queue Management
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {ResourcesOfWorkQueueVO} from './ResourcesOfWorkQueueVO';

export interface PagedResourcesOfResourcesOfWorkQueueVO {
  content?: Array<ResourcesOfWorkQueueVO>;
  last?: boolean;
  totalPages?: number;
  totalElements?: number;
  size?: number;
  number?: number;
  first?: boolean;
  numberOfElements?: number;
}
