/**
 * work-queue-management
 * Services to support Work Queue Management
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface QueueNameVO {
  queueId?: number;
  category?: string;
  queueType?: string;
  workType?: string;
  code?: string;
  name?: string;
  description?: string;
}
