/**
 * fox-claims
 * Custom developed service operations to support core claim processing and claim history inquiry.  Some services interact with modernized code.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UpdateItemModel} from './update-item.model';

export class UpdateEobBilllineModel {
    billLineKey?: string;
    billLineChAcctPartNum?: string;
    billLineNum?: string;
    billLineDosFrom?: UpdateItemModel;
    billLineDosTo?: UpdateItemModel;
    billLineExceptionInd?: UpdateItemModel;
    billLineSrvAccum1?: UpdateItemModel;
    billLineSrvAccum2?: UpdateItemModel;
    billLineBenefitPeriodNum?: UpdateItemModel;
    billLineBenefitPeriodDays?: UpdateItemModel;
    billLineDateOfAccident?: UpdateItemModel;
    billLineServiceCode?: UpdateItemModel;
    billLineTypeCode?: UpdateItemModel;
}
