export enum InfoMessages {
  'NEW TEMPLATE RECORD WILL BE ADDED',
  'TRANSACTION PENDING VERIFICATION',
  'WARNING - NO FIELDS HAVE BEEN UPDATED',
  'TRANSACTION CANCELED'
}

export enum WarningMessages {
  'PLEASE VERIFY SET QUALITY TEMPLATE',
  'PLEASE VERIFY SET QUALITY COMBINATION OVERRIDES'
}

export enum SuccessMessages {
  'TRANSACTION COMPLETED'
}
