/**
 * bpm-mediator
 * BPM Mediator to facilitate interactions between BPM and other services
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export class AddressVO {
  addressLine1?: string;
  addressLine2?: string;
  addressLine3?: string;
  cityNameText?: string;
  stateProvinceCode?: string;
  postalCode?: string;
  countryCode?: string;
  countrySubCode?: string;
  city?: string;
  state?: string;
  address?: AddressVO;
  startDt?: string;
  stopDt?: string;
  zip?: string;
}
