/**
 * bpm-mediator
 * BPM Mediator to facilitate interactions between BPM and other services
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {MemberVO} from './MemberVO';
import {ServiceDateVO} from './ServiceDateVO';

export interface MemberValidationRequestVO {
  claimTrackingId?: string;

  source?: number;

  serviceDates?: ServiceDateVO;

  member?: MemberVO;

}
