/**
 * bpm-mediator
 * BPM Mediator to facilitate interactions between BPM and other services
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {MemberLookupProcessInfo} from './MemberLookupProcessInfo';

export interface ResourceOfMemberLookupProcessInfo {
  memberLookupProcess?: MemberLookupProcessInfo;

  _links?: { [key: string]: { [key: string]: string; }; };

}
