/**
 * fox-audit
 * Custom developed service operations to support the Common Business Audit solution for FOX.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuditEventObjectDetailsVO } from './AuditEventObjectDetailsVO';

export interface AuditRequestVO {
    businessCode: string;
    businessId: string;
    eventCode: string;
    eventDetails?: string;
    eventNote?: string;
    createdBy: string;
    createDate: string;
    eventObjectDetails?: Array<AuditEventObjectDetailsVO>;
}
