import {PageMetadataVO} from '../../PageMetadataVO';
/**
 * ACES Mediator
 * This is the ACES Mediator REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: gabrielle_goodwin@uhc.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {ResourcesListOfResourceOfMaterialEOBVO} from './ResourcesListOfResourceOfMaterialEOBVO';

export interface PagedResourcesOfResourceOfMaterialEOBVO {
  _embedded?: ResourcesListOfResourceOfMaterialEOBVO;
  links?: { [key: string]: { [key: string]: string; }; };
  page?: PageMetadataVO;
}
