import {Oprec1Record, QualityCommAreaFieldsFor06o75, OprecRecord, ECImageRecord} from '@fox/shared';
// import { ECImageRecordPO } from '../../common/pos/ecimage-record-po.model';
// import { OprecRecordPO } from '../../common/pos/oprec-record-po.model';

/**
 * Model class WorkStorage
 * Path: screenbean/qltyrvwrvlddupbil
 * Model: com::uhc::aarp::fox::domain::screenbean::qltyRvwRvldDupBil::WorkStorage
 */
export class WorkStorage {
  qrrDupSub = 0;
  prevScreenSub = 0;
  sub = 0;
  qualCommLength = 0;
  billScrnSub = 0;
  chrgSub = 0;
  headSub = 0;
  blSub = 0;
  qualityCommAreaFieldsFor06o75 = new QualityCommAreaFieldsFor06o75();
  cl1ProviderTp = '';
  cl1ProviderName = '';
  cl1FromDate = 0;
  cl1ToDate = 0;
  cl1NoOfDays = 0;
  cl1PreExist = '';
  cl1Charge = 0;
  cl1IcuFromDate = 0;
  cl1IcuToDate = 0;
  cl1IcuDays = 0;
  cl1DateOfSurgery = 0;
  cl2EcGroupName = '';
  cl2EcCptCodeHdg = '';
  cl2EcCptCode = '';
  cl2EcTotalBilledAmtHdg = '';
  cl2EcTotalBilledAmt = 0;
  cl3NoOfVisits = 0;
  cl3CoveredExpense = 0;
  cl3PreExisting = '';
  cl4NoOfShifts = 0;
  cl4NoOfHours = 0;
  cl4EligibleCharge = 0;
  cl5AarpPharmacy = '';
  cl6NoOfServices = 0;
  oprecRecord = new OprecRecord();
  ecImageRecord = new ECImageRecord();
  wsQualityClaim = '';
  wsBillFromDate = 0;
  wsBillToDate = 0;
  maximumMessageInd = '';
  lineCount = 0;
  newChargeLineInd = '';
  blPlanCode = '';
  blServiceCode = '';
  blTypeCode = '';
  blProviderName = '';
  blFromDate = 0;
  blToDate = 0;
  blToDateX = '';
  blNoOfDays = 0;
  blNoOfDaysN = 0;
  blPreExist = '';
  blCharge = 0;
  blBenefit = 0;
  blSpouseInd = '';
  blAssignInd = '';
  blReply = '';
  blCoveredExpense = 0;
  blNoOfVisits = 0;
  blNoOfShifts = 0;
  blNoOfHours = 0;
  blEligibleCharge = 0;
  blAarpPharmacy = '';
  blNoOfServices = 0;
  blProviderOrEombDate = '';
  blAmountBilled = 0;
  blAmountApproved = 0;
  blMedicarePayment = 0;
  blPartBDeduct = 0;
  blCoIns = 0;
  blNo = 0;
  holdDate = 0;
  blcClaimnoHdg = '';
  blcClaimno = 0;
  blcError = '';
  blEcGroupName = '';
  blEcCptCodeHdg = '';
  blEcCptCode = '';
  blEcTotalBilledAmtHdg = '';
  blEcTotalBilledAmt = 0;
  wsSaveScreenNo = 0;
  wsSaveDupBillType = '';
  wsSaveChrgLineNo = 0;
  commandEnteredInd = '';
  cl6Service = '';
  cl6Type = '';
  cl7ServiceCode = '';
  cl7ServiceCodeType = '';
  cl7PlanCode = '';
  cl7AmountBilled = 0;
  cl7AmountApproved = 0;
  cl7MedicarePayment = 0;
  cl7PartbDeduct = 0;
  cl7AssignInd = '';
  cl7CoIns = 0;
  cl8Pct = 0;
  cl8Benefit = 0;
  cl8ProcCode = '';
  oprec1Record = new Oprec1Record();
}
