/**
 * Model class ElctrCmnArea
 * Path: bean/commonarea
 * Model: com::uhc::aarp::fox::domain::bean::commonarea::ElctrCmnArea
 * Legacy Mapping: ELECTRONIC-COMMAREA
 */
export class ElctrCmnArea {
  prevEccStatusInd = '';
  ub92Ind = '';
  compasMcnInd = '';
  provHosp15pos = '';
  eombDate = '';
  erisaPpAdded = '';
  medClmCntlNo = '';
  claimTotalAppAmt = 0;
  claimTotalCoinsurAmt = 0;
  clearingHouseNmbr = '';
  claimProcessInd = '';
  ppCnt = 0;
  chPpNum = 0;
  chPpVar01 = '';
  chPpVar02 = '';
  chPpVar03 = '';
  chPpVar04 = '';
  chPpVar05 = '';
  chPpVar06 = '';
  claimServFromCc = '';
  claimServFromYymmdd = '';
  claimServToCc = '';
  claimServToYymmdd = '';
  rpd08o42ErrorSwitch = '';
  assigneeProviderKey = 0;
  assignProviderId = '';
  assignTaxIdNumber = '';
  assignTaxIdInd = '';
  assignName = '';
  assignAddress = '';
  assignGroupNameCode = '';
  assignInd = '';
  ecErrFile = '';
  ecErrFunction = '';
  ecErrReturnCode = '';
  ecErrReturnMessage = '';
  claimRrKey = 0;
  level = '';
  suspErrorCode = '';
  surname = '';
  firstInit = '';
  date = '';
  seqNo = 0;
  pfTaxIdType = '';
  pfTaxIdNumber = '';
  pfMedicareKey = '';
  pfPName = '';
  pfNameType = '';
  pfStr1 = '';
  pfStr2 = '';
  pfCity = '';
  pfState = '';
  pfZipCode = '';
  pfPhoneArea = 0;
  pfPhoneNo = 0;
  assignmentInd = '';
  rejectErrorCodes = '';
  claimIsAssign = '';
  hicNumber = '';
  manualProcessInd = '';
  pfZipFill = '';
  secProvCrossoverArea = '';
  filler = '';
  filler1 = '';
  filler3 = '';
}
