export enum OP {
  READ_MEMBER = 'OP_READ_MEMBER',
  REASSIGN_MEMBER_LOOKUP = 'OP_REASSIGN_MEMBER_LOOKUP',
  VIEW_PAYMENT = 'OP_VIEW_PAYMENT',
  MAINTAIN_PAYMENT = 'OP_MAINTAIN_PAYMENT',
  AUTHORIZE_PAYMENT_ACTION = 'OP_AUTHORIZE_PAYMENT_ACTION',
  VIEW_CLAIM_IMAGE = 'OP_VIEW_CLAIM_IMAGE',

  VIEW_DOCUMENT = 'OP_VIEW_DOCUMENT',
  EDIT_DOCUMENT = 'OP_EDIT_DOCUMENT',
  DELETE_DOCUMENT = 'OP_DELETE_DOCUMENT',

  MAINTAIN_WORKQUEUE = 'OP_MAINTAIN_WORKQUEUE',
  MAINTAIN_CSS_WQ = 'OP_MAINTAIN_CSS_WQ',
  MAINTAIN_SIU_WQ = 'OP_MAINTAIN_SIU_WQ',
  MAINTAIN_STD_WQ = 'OP_MAINTAIN_STD_WQ',
  MAINTAIN_EH_WQ = 'OP_MAINTAIN_EH_WQ',

  VIEW_CLAIM_NOTE = 'OP_VIEW_CLAIM_NOTE',
  MAINTAIN_CLAIM_NOTE = 'OP_MAINTAIN_CLAIM_NOTE',

  MEMBER_PROFILE = 'OP_MEMBER_PROFILE',

  SEND_EOB = 'OP_SEND_EOB',
  SEND_RA = 'OP_SEND_RA',
  REPLACE_EOB = 'OP_REPLACE_EOB',
  REPLACE_RA = 'OP_REPLACE_RA',
  RECOVER_OVERPAYMENT = 'OP_RECOVER_OVERPAYMENT',
  PROCESS_CLAIM = 'OP_PROCESS_CLAIM',

  VIEW_DEPOSIT = 'OP_VIEW_DEPOSIT',
  UPDATE_DEPOSIT = 'OP_UPDATE_DEPOSIT_SUMMARY',

  VIEW_TRC = 'OP_VIEW_TRC',
  MAINTAIN_TRC = 'OP_MAINTAIN_TRC'
}
