/**
 * fox-pre-adjudication
 * Orchestrates the pre-adjudication process, supporting both auto and manual processing of claims through provider validation.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {HttpClient, HttpEvent, HttpHeaders, HttpResponse} from '@angular/common/http';
import {Inject, Injectable, Optional} from '@angular/core';
import {Observable} from 'rxjs';
import {Configuration} from '../configuration';
import {BASE_PATH} from '../variables';
import {ProviderValidationAutoRequestVO} from './model/ProviderValidationAutoRequestVO';
import {ProviderValidationAutoResponseVO} from './model/ProviderValidationAutoResponseVO';
import {ProviderValidationManualRequestVO} from './model/ProviderValidationManualRequestVO';
import {ProviderValidationManualResponseVO} from './model/ProviderValidationManualResponseVO';

@Injectable({
  providedIn: 'root'
})
export class ProviderValidationService {
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();

  protected basePath = '';

  constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
    if (basePath) {
      this.basePath = basePath;
    }
    if (configuration) {
      this.configuration = configuration;
      this.basePath = basePath || configuration.basePath || this.basePath;
    }
  }

  /**
   * Handle Request
   * To submit a provider for validation
   * @param providerValidationAutoRequest To submit a member for validation
   * @param requestCorrelationId Initial Request GUID
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public validateProviderAuto(providerValidationAutoRequest: ProviderValidationAutoRequestVO, requestCorrelationId?: string, observe?: 'body', reportProgress?: boolean): Observable<ProviderValidationAutoResponseVO>;
  public validateProviderAuto(providerValidationAutoRequest: ProviderValidationAutoRequestVO, requestCorrelationId?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ProviderValidationAutoResponseVO>>;
  public validateProviderAuto(providerValidationAutoRequest: ProviderValidationAutoRequestVO, requestCorrelationId?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ProviderValidationAutoResponseVO>>;
  public validateProviderAuto(providerValidationAutoRequest: ProviderValidationAutoRequestVO, requestCorrelationId?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

    if (providerValidationAutoRequest === null || providerValidationAutoRequest === undefined) {
      throw new Error('Required parameter providerValidationAutoRequest was null or undefined when calling validateProviderAuto.');
    }

    let headers = this.defaultHeaders;
    if (requestCorrelationId !== undefined && requestCorrelationId !== null) {
      headers = headers.set('RequestCorrelationId', String(requestCorrelationId));
    }

    // authentication (oauth) required
    if (this.configuration.accessToken) {
      const accessToken = typeof this.configuration.accessToken === 'function'
        ? this.configuration.accessToken()
        : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }

    // to determine the Accept header
    const httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.post<ProviderValidationAutoResponseVO>(`${this.basePath}/api/providervalidation/auto`,
      providerValidationAutoRequest,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Handle Request
   * To submit a provider for validation
   * @param providerValidationAutoRequest To submit a member for validation
   * @param requestCorrelationId Initial Request GUID
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public validateProviderManual(providerValidationAutoRequest: ProviderValidationManualRequestVO, requestCorrelationId?: string, observe?: 'body', reportProgress?: boolean): Observable<ProviderValidationManualResponseVO>;
  public validateProviderManual(providerValidationAutoRequest: ProviderValidationManualRequestVO, requestCorrelationId?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ProviderValidationManualResponseVO>>;
  public validateProviderManual(providerValidationAutoRequest: ProviderValidationManualRequestVO, requestCorrelationId?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ProviderValidationManualResponseVO>>;
  public validateProviderManual(providerValidationAutoRequest: ProviderValidationManualRequestVO, requestCorrelationId?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

    if (providerValidationAutoRequest === null || providerValidationAutoRequest === undefined) {
      throw new Error('Required parameter providerValidationAutoRequest was null or undefined when calling validateProviderManual.');
    }

    let headers = this.defaultHeaders;
    if (requestCorrelationId !== undefined && requestCorrelationId !== null) {
      headers = headers.set('RequestCorrelationId', String(requestCorrelationId));
    }

    // authentication (oauth) required
    if (this.configuration.accessToken) {
      const accessToken = typeof this.configuration.accessToken === 'function'
        ? this.configuration.accessToken()
        : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }

    // to determine the Accept header
    const httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.post<ProviderValidationManualResponseVO>(`${this.basePath}/api/providervalidation/manual`,
      providerValidationAutoRequest,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = 'multipart/form-data';
    for (const consume of consumes) {
      if (form === consume) {
        return true;
      }
    }
    return false;
  }

}
