/**
 * fox-claims
 * Monolithic-style application containing generated components from legacy code modernization and custom developed APIs to support core claim processing.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {HttpClient, HttpEvent, HttpHeaders, HttpParams, HttpResponse} from '@angular/common/http';
import {Inject, Injectable, Optional} from '@angular/core';
import {Observable} from 'rxjs';
import {Configuration} from '../configuration';
import {CustomHttpUrlEncodingCodec} from '../encoder';
import {BASE_PATH} from '../variables';
import {OperationalReportVO} from './model/OperationalReportVO';
import {ReferenceValueVO} from '../ReferenceValueVO';

@Injectable({
  providedIn: 'root'
})
export class ReferencesApi {
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();

  protected basePath = '';

  constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
    if (basePath) {
      this.basePath = basePath;
    }
    if (configuration) {
      this.configuration = configuration;
      this.basePath = basePath || configuration.basePath || this.basePath;
    }
  }

  /**
   * List of category codes
   * Retrieve a list of category codes
   * @param name Table names to query
   * @param requestCorrelationId Initial Request GUID
   * @param id Reference value id
   * @param code Reference coded value
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public listCategoryCodes(name: string, requestCorrelationId?: string, id?: number, code?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<ReferenceValueVO>>;
  public listCategoryCodes(name: string, requestCorrelationId?: string, id?: number, code?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ReferenceValueVO>>>;
  public listCategoryCodes(name: string, requestCorrelationId?: string, id?: number, code?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ReferenceValueVO>>>;
  public listCategoryCodes(name: string, requestCorrelationId?: string, id?: number, code?: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (name === null || name === undefined) {
      throw new Error('Required parameter name was null or undefined when calling listCategoryCodes.');
    }

    let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
    if (name !== undefined) {
      queryParameters = queryParameters.set('name', <any>name);
    }
    if (id !== undefined) {
      queryParameters = queryParameters.set('id', <any>id);
    }
    if (code !== undefined) {
      queryParameters = queryParameters.set('code', <any>code);
    }

    let headers = this.defaultHeaders;
    if (requestCorrelationId !== undefined && requestCorrelationId !== null) {
      headers = headers.set('RequestCorrelationId', String(requestCorrelationId));
    }

    // to determine the Accept header
    const httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    if (this.configuration.accessToken) {
      const accessToken = typeof this.configuration.accessToken === 'function'
        ? this.configuration.accessToken()
        : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];

    return this.httpClient.get<Array<ReferenceValueVO>>(`${this.basePath}/api/reference/`,
      {
        params: queryParameters,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * List of operational reports and their URL
   * Retrieve a list of operational reports
   * @param requestCorrelationId Initial Request GUID
   * @param category Values to query for report function
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public listOperationalReport(requestCorrelationId?: string, category?: string, observe?: 'body', reportProgress?: boolean): Observable<OperationalReportVO>;
  public listOperationalReport(requestCorrelationId?: string, category?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<OperationalReportVO>>;
  public listOperationalReport(requestCorrelationId?: string, category?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<OperationalReportVO>>;
  public listOperationalReport(requestCorrelationId?: string, category?: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
    if (category !== undefined) {
      queryParameters = queryParameters.set('category', <any>category);
    }

    let headers = this.defaultHeaders;
    if (requestCorrelationId !== undefined && requestCorrelationId !== null) {
      headers = headers.set('RequestCorrelationId', String(requestCorrelationId));
    }

    // authentication (oauth) required
    if (this.configuration.accessToken) {
      const accessToken = typeof this.configuration.accessToken === 'function'
        ? this.configuration.accessToken()
        : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }

    // to determine the Accept header
    const httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];

    return this.httpClient.get<OperationalReportVO>(`${this.basePath}/api/reference/report`,
      {
        params: queryParameters,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = 'multipart/form-data';
    for (const consume of consumes) {
      if (form === consume) {
        return true;
      }
    }
    return false;
  }

}
