import { DrugsChargeArea } from './drugs-charge-area.model';
import { ExceptionChargeArea } from './exception-charge-area.model';
import { HomeHlthOutHospChargeArea } from './home-hlth-out-hosp-charge-area.model';
import { HospitalChargeArea } from './hospital-charge-area.model';
import { MedSuppChargeArea } from './med-supp-charge-area.model';
import { MedicalChargeArea } from './medical-charge-area.model';
import { NursingChargeArea } from './nursing-charge-area.model';
import { OprecBillRecords } from './oprec-bill-records.model';
import { OprecHospEobData } from './oprec-hosp-eob-data.model';
import { OprecSuspendedReasonCodes } from './oprec-suspended-reason-codes.model';
import { OprecVariableInfo } from './oprec-variable-info.model';
import { Oprec2Record } from './oprec2-record.model';

/**
 * Model class Oprec1Record
 * Path: oprecqr
 * Model: com::uhc::aarp::fox::domain::oprecQR::Oprec1Record
 */
export class Oprec1Record {
  claimNumber = 0;
  claimStatus = '';
  operLocation = 0;
  dateToQuality = '';
  qualitySeqNumber = 0;
  crossReferenceNumber1 = 0;
  crossReferenceNumber2 = 0;
  crossReferenceNumber3 = 0;
  communDate = '';
  communSeqNo = 0;
  pacsId = 0;
  icdCodes = '';
  deceasedInd = 0;
  operatorId = 0;
  terminalId = '';
  insuredDob = '';
  insuredSex = '';
  insuredSurname = '';
  insuredFirstName = '';
  insuredMiddleInitial = '';
  insuredHonorTitle = 0;
  insuredStreet1 = '';
  insuredStreet2 = '';
  insuredCity = '';
  insuredState = '';
  insuredZip = '';
  altSurname = '';
  altFirstName = '';
  altMiddleInitial = '';
  altHonorTitle = 0;
  altStreet1 = '';
  altStreet2 = '';
  altCity = '';
  altState = '';
  altZip = '';
  assignInd = '';
  assigneeProviderKey = 0;
  assignProviderId = '';
  assignTaxIdNumber = '';
  assignTaxIdInd = '';
  assignSurname = '';
  assignFirst = '';
  assignMiddleInitial = '';
  assignDegreeTitle = '';
  assignStreet1 = '';
  assignStreet2 = '';
  assignCity = '';
  assignState = '';
  assignZip = '';
  assignGroupNameCode = '';
  dateProcessed = new Date();
  dateCompleted = new Date();
  serviceFromDate = new Date();
  serviceToDate = new Date();
  paidToDate = new Date();
  letterPlans = '';
  splitClaimInd = '';
  qualityFlag = '';
  hospProvPercent1 = 0;
  hospProvPercent2 = 0;
  qualityRevalidationInd = '';
  processFlag = '';
  newProv = '';
  foreignProvider = '';
  origOperId = 0;
  origLoc = 0;
  patientNumber = '';
  dateToSuspense = new Date();
  qualityOperId = 0;
  qualityTerminalId = '';
  mostRecentQualityErrors = [];
  originalQualityErrors = [];
  originalQualityReasons = [];
  mostRecentQualityReasons = [];
  bypassCautionMessages = '';
  specialMemoLine1 = '';
  specialMemoLine2 = '';
  specialMemoLine3 = '';
  specialMemoLine4 = '';
  patternParagraph1 = 0;
  patternParagraph2 = 0;
  patternParagraph3 = 0;
  patternParagraph4 = 0;
  patternParagraph5 = 0;
  patternParagraph6 = 0;
  patternParagraph7 = 0;
  checkNoPayInd = 0;
  checkSeries = 0;
  eobType = '';
  checkDate = new Date();
  payAdjustAmt = 0;
  totalBenefitAmt = 0;
  checkNumber = 0;
  checkAmount = 0;
  assignPayAdjustAmt = 0;
  assignTotBenefitAmt = 0;
  assignCheckNumber = 0;
  assignCheckAmount = 0;
  billLineInd = 0;
  olPayAfterExPlanInd = '';
  olApprovalCode = 0;
  olAcceptCodes1 = '';
  olAcceptCodes2 = '';
  olAcctTransInd = '';
  bulkCheckAmount = 0;
  bulkIndicator = '';
  providerCheckSeries = 0;
  insuredOutputId = '';
  eobSortInd = '';
  providerOutputId = '';
  recTypeByte1 = '';
  recTypeByte2 = '';
  buwRefundInd = '';
  buwInd = '';
  extendHoldElig = '';
  replaceTo = '';
  disbursedOprecFiller = '';
  batchFiller = {};
  communDate1 = new Date();
  communSeqNo1 = 0;
  complianceDate = new Date();
  rlseReason = '';
  supprInd = '';
  fundsAvailDate = new Date();
  achInd = '';
  hospEobData = [];
  billRecords = [];
  variableInfo = [];
  suspendedReasonCodes = [];
  hospitalChargeArea = new HospitalChargeArea();
  nursingChargeArea = new NursingChargeArea();
  homeHlthOutHospChargeArea = new HomeHlthOutHospChargeArea();
  drugsChargeArea = new DrugsChargeArea();
  medicalChargeArea = new MedicalChargeArea();
  exceptionChargeArea = new ExceptionChargeArea();
  medSuppChargeArea = new MedSuppChargeArea();
}
