/**
 * fox-claims
 * Custom developed service operations to support core claim processing and claim history inquiry.  Some services interact with modernized code.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {HttpClient, HttpEvent, HttpHeaders, HttpParams, HttpResponse} from '@angular/common/http';
import {Inject, Injectable, Optional} from '@angular/core';
import {Observable} from 'rxjs';
import {Configuration} from '../configuration';
import {CustomHttpUrlEncodingCodec} from '../encoder';
import {BASE_PATH} from '../variables';
import {ListOfAuditResponseVO} from './model/ListOfAuditResponseVO';

@Injectable({
  providedIn: 'root'
})
export class AuditApi {
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();

  protected  basePath = '';

  constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
    if (basePath) {
      this.basePath = basePath;
    }
    if (configuration) {
      this.configuration = configuration;
      this.basePath = basePath || configuration.basePath || this.basePath;
    }
  }

  /**
   * Retrive  audit log
   * To retrive an audit log by business Id and business code by calling Fox Audit
   * @param businessId Business ID of audit event
   * @param businessCode Business Code of audit event
   * @param requestCorrelationId Initial Request GUID
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param filterSystemAudit flag to set it true.

   */

  public obtainAuditLog(businessId: string, businessCode: string, requestCorrelationId?: string, observe?: 'body', filterSystemAudit?: string, reportProgress?: boolean): Observable<ListOfAuditResponseVO>;
  public obtainAuditLog(businessId: string, businessCode: string, requestCorrelationId?: string, observe?: 'response', filterSystemAudit?: string, reportProgress?: boolean): Observable<HttpResponse<ListOfAuditResponseVO>>;
  public obtainAuditLog(businessId: string, businessCode: string, requestCorrelationId?: string, observe?: 'events', filterSystemAudit?: string, reportProgress?: boolean): Observable<HttpEvent<ListOfAuditResponseVO>>;
  public obtainAuditLog(businessId: string, businessCode: string, requestCorrelationId?: string, observe: any = 'body', filterSystemAudit: string = 'true', reportProgress: boolean = false ): Observable<any> {
    if (businessId === null || businessId === undefined) {
      throw new Error('Required parameter businessId was null or undefined when calling obtainAuditLog.');
    }

    if (businessCode === null || businessCode === undefined) {
      throw new Error('Required parameter businessCode was null or undefined when calling obtainAuditLog.');
    }

    let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
    if (filterSystemAudit !== undefined) {
      queryParameters = queryParameters.set('filterSystemAudit', 'true');
    }

    let headers = this.defaultHeaders;
    if (requestCorrelationId !== undefined && requestCorrelationId !== null) {
      headers = headers.set('RequestCorrelationId', String(requestCorrelationId));
    }

    // authentication (oauth) required
    if (this.configuration.accessToken) {
      const accessToken = typeof this.configuration.accessToken === 'function'
        ? this.configuration.accessToken()
        : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }

    // to determine the Accept header
    const httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];

    return this.httpClient.get<ListOfAuditResponseVO>(`${this.basePath}/api/audit/log/${encodeURIComponent(String(businessCode))}/${encodeURIComponent(String(businessId))}`,
      {
        params: queryParameters,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */

  private canConsumeForm(consumes: string[]): boolean {
    const form = 'multipart/form-data';
    for (const consume of consumes) {
      if (form === consume) {
        return true;
      }
    }
    return false;
  }

}
