import {ScreenDate} from './screen-date.model';
import {ScreenDate2} from './screen-date2.model';
import {ScreenDate3} from './screen-date3.model';
import {WkPlanData} from './wk-plan-data.model';
import {WorkIcdCode} from './work-icd-code.model';
import {WsDateCcyy} from './ws-date-ccyy.model';
import {WsDbDateFormat} from './ws-db-date-format.model';
import {WsNpChrgIoArea} from './ws-np-chrg-io-area.model';
import {WsNpChrgLineRec} from './ws-np-chrg-line-rec.model';
import {WsNpTsqName} from './ws-np-tsq-name.model';
import {WsScreenCptField} from './ws-screen-cpt-field.model';
import {WsSqlErrorMsg} from './ws-sql-error-msg.model';
import {WsTsqDateFormat} from './ws-tsq-date-format.model';
import {WsTsqErrorMsg} from './ws-tsq-error-msg.model';
/**
 * Model class WorkStorage
 * Path: screenbean/procclmnopaychrg
 * Model: com::uhc::aarp::fox::domain::screenbean::procclmnopaychrg::WorkStorage
 */
export class WorkStorage {
  sub = 0;
  sub1 = 0;
  sub2 = 0;
  sub3 = 0;
  errCnt = 0;
  cptSub = 0;
  plSub = 0;
  wsBillLinesEnteredCtr = 0;
  npChrgLineCtr = 0;
  wsCount = 0;
  wsCptValued = 0;
  commandEnteredInd = '';
  curDateYmdPlus4 = 0;
  screenDate = new ScreenDate();
  screenDate2 = new ScreenDate2();
  screenDate3 = new ScreenDate3();
  workDate = 0;
  saveSerDate = 0;
  saveSerFromYmd = 0;
  saveSerToYmd = 0;
  tosSerFromYmd = 0;
  tosSerToYmd = 0;
  saveEffYmd = 0;
  saveTermYmd = 0;
  wsDateCcyy = new WsDateCcyy();
  wsDateCcyy9 = 0;
  wsHoldDateCcyy = 0;
  wsDbDateFormat = new WsDbDateFormat();
  wsTsqDateFormat = new WsTsqDateFormat();
  wsTsqDateFormat9 = 0;
  wsServiceYymm = 0;
  workIcdCode = new WorkIcdCode();
  wkPlanData = new WkPlanData();
  saveProvider = '';
  saveProvider9 = 0;
  errMsg = '';
  yearDivide = 0;
  leapChk = 0;
  tosMatchInd = '';
  validNopayTos = '';
  wsDosFromCymd = 0;
  wsDosToCymd = 0;
  holdScreenPlanInds: string[] = [];
  wsScreenCptField = new WsScreenCptField();
  wsProvider = '';
  workDateMm = 0;
  workDateDd = 0;
  workDateYy = 0;
  wsServiceYy = '';
  wsServiceMm = '';
  workIcdCodePos: string[] = [];
  curDateYmdP4Yy = 0;
  curDateYmdP4Mm = 0;
  curDateYmdP4Dd = 0;
  saveSerDateMm = 0;
  saveSerDateDd = 0;
  saveSerDateYy = 0;
  serFromYy = 0;
  serFromMm = 0;
  serFromDd = 0;
  serToYy = 0;
  serToMm = 0;
  serToDd = 0;
  tosSerFromYy = 0;
  tosSerFromMm = 0;
  tosSerFromDd = 0;
  tosSerToYy = 0;
  tosSerToMm = 0;
  tosSerToDd = 0;
  saveEffYy = 0;
  saveEffMm = 0;
  saveEffDd = 0;
  saveTrmYy = 0;
  saveTrmMm = 0;
  saveTrmDd = 0;
  readErrorRpdiskqb = '';
  linkRpd06o24Error = '';
  wsTsqErrorMsg = new WsTsqErrorMsg();
  wsSqlErrorMsg = new WsSqlErrorMsg();
  badTempqRead = '';
  forcedToNopay = '';
  validPlanInd = '';
  ppoPlanInd = '';
  dateErr = '';
  invalidProInd = '';
  dosFromEnteredInd = '';
  dosToEnteredInd = '';
  tsqNpEofInd = '';
  csrChrgEofInd = '';
  csrIcdcEofInd = '';
  wsNpItemNum = 0;
  wsNpTsqNumItems = 0;
  wsNpTsqName = new WsNpTsqName();
  wsNpChrgIoArea = new WsNpChrgIoArea();
  wsNpChrgLineRecs: WsNpChrgLineRec[] = [];
  finishDi316 = '';
  icd1 = '';
  icd3 = '';
  icd2 = '';
}
