/**
 * fox-claims-finance
 * Custom developed service operations to support claim financial processing, such as payment, deposit, and TRC processing.  Services interact with modernized code.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface OverpaymentRequestVO {
  status?: string;
  errorType?: string;
  errorCode?: string;
  amountRepaidProvider?: number;
  amountRepaidInsured?: number;
  amountUnresolvedProvider?: number;
  amountUnresolvedInsured?: number;
  amountWaivedProvider?: number;
  amountWaivedInsured?: number;
}
