/**
 * fox-claims-finance
 * Custom developed service operations to support claim financial processing, such as payment, deposit, and TRC processing.  Services interact with modernized code.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export class OverpaymentRecoveryInputFileVO {
  action?: OverpaymentRecoveryInputFileVO.ActionEnum;
  overpaymentRecoveryInputFile?: string;
  vendor?: string;
  reportDate?: string;
}

export namespace OverpaymentRecoveryInputFileVO {
  export type ActionEnum = 'R' | 'P' | 'U' | 'C';
  export const ActionEnum = {
    Retrieve: 'R' as ActionEnum,
    Payment: 'P' as ActionEnum,
    Update: 'U' as ActionEnum,
    Cancel: 'C' as ActionEnum
  };
}
