/**
 * fox-claims-finance
 * Custom developed service operations to support claim financial processing, such as payment, deposit, and TRC processing.  Services interact with modernized code.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PageMetadataVO } from '../../PageMetadataVO';
import { ResourceslistOfOverpaymentRecoveryVO } from './ResourceslistOfOverpaymentRecoveryVO';

export interface PagedResourcesofOverpaymentRecoveryVO {
  _embedded?: ResourceslistOfOverpaymentRecoveryVO;
  _links?: { [key: string]: { [key: string]: string; }; };
  page?: PageMetadataVO;
}
