import { CorpsNbrDivCSnDDivTablePO } from '../../../core/pos/corps-nbr-div-csn-ddiv-table-po.model';
import { CorpsNbrDivPO } from '../../../core/pos/corps-nbr-div-po.model';
import { CorpsNbrHeadPO } from '../../../core/pos/corps-nbr-head-po.model';
import { CumOperStatPO } from '../../../core/pos/cum-oper-stat-po.model';
import { OperatorFilePO } from '../../../core/pos/operator-file-po.model';
import { OperatorStatsRecordPO } from '../../../core/pos/operator-stats-record-po.model';
import { StringUtils } from '../../services/string-utils.service';
import { WsCommarea } from './ws-commarea.model';

/**
 * Model class WorkStorage
 * Path: screenbean/rvwoperatorstat
 * Model: com::uhc::aarp::fox::domain::screenbean::rvwoperatorstat::WorkStorage
 * Legacy Mapping: PROGRAM-WORK-AREAS
 */
export class WorkStorage {
  commandEnteredInd = '';
  foundInd = '';
  leapYr = 0;
  leapChk = 0;
  endFound = '';
  errorInd = '';
  dailyInd = '';
  mondayInd = '';
  siteScreenDone = '';
  wsHours = 0;
  wsDecimalHours = 0;
  wsMinutes = 0;
  commandCommLen = 0;
  primaryKeyLen = 0;
  altKeyLen = 0;
  opstatFileLen = 0;
  commareaLength = 0;
  commareaLengthMove = 0;
  siteOfEnteredDiv = '';
  locOfEnteredIons = 0;
  divOfEnteredIons = 0;
  enteredLoc = 0;
  divOfEnteredLoc = 0;
  errMsg = '';
  errCnt = 0;
  dateErr = '';
  recordFoundInd = '';
  blankSw = '';
  endDateFlag = '';
  foundFlag = '';
  endDateReq = 0;
  yearDivide = 0;
  s1 = 0;
  s2 = 0;
  julYy = 0;
  julianDays = 0;
  julianRemainder = 0;
  wsYear = 0;
  num1 = 0;
  num2 = 0;
  num3 = 0;
  divNumR = '';
  saveEndDate = '';
  workDate = '';
  workDate2 = '';
  workDate3 = '';
  beginDateYmd = '';
  endDateYmd = '';
  reqidFld = 0;
  userid = '';
  useridR = 0;
  operatorRecKey = 0;
  inputLocationNum = 0;
  constant999 = 0;
  sub = 0;
  sub2 = 0;
  fsub = 0;
  cntr = 0;
  inSub = 0;
  outSub = 0;
  workSub = 0;
  divSub = 0;
  wsTotMinutes = 0;
  tabDays: number[] = [];
  ciWorkDate = '';
  altKeyDate = 0;
  altKeyDivR = '';
  altKeyLoc = 0;
  opstatDiv = 0;
  opstatLoc = 0;
  primaryKeyDate = 0;
  primaryKeyUseridR = '';
  wsCSDateKey = 0;
  wsCSRecordType = 0;
  wsCSSite = 0;
  wsCSDivision = 0;
  wsCSLocation = 0;
  wsCSOperator = 0;
  holdAreaOutputs = '';
  wsAccumHours = 0;
  wsAccumMinutes = 0;
  wsRecHours = 0;
  wsRecMinutes = 0;
  wsCommarea = new WsCommarea();
  holdAreaInput = '';
  cDate1 = '';
  cDate2 = '';
  wsGregDate = '';
  wsJulDate = '';
  julDdd = 0;
  listEmpty = false;
  cumOperStatPO_BegnDtRng = new Date();
  cumOperStatPO_EndDtRng = new Date();
  cumOperStatPO_ActulLvl = 0;
  cumOperStatPO_FullTmInd = '';
  cumOperStatPO_Ld = '';
  cumOperStatPO_CollGrad = '';
  cumOperStatPO_Trn = '';
  cumOperStatPO_Typ2Ind = '';
}
