/**
 * Letter Writing Mediator
 * This is the letter-writing mediator REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: gaohly_yang@uhc.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {HttpClient, HttpEvent, HttpHeaders, HttpResponse} from '@angular/common/http';
import {Inject, Injectable, Optional} from '@angular/core';

import {Observable} from 'rxjs';
import {Configuration} from '../configuration';

import {BASE_PATH} from '../variables';
import {GenerateLetterRequestVO} from './model/GenerateLetterRequestVO';
import {SearchLetterRequestVO} from './model/SearchLetterRequestVO';
import {SearchLetterResponseVO} from './model/SearchLetterResponseVO';

@Injectable({
  providedIn: 'root'
})
export class LetterWritingApi {
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();

  protected basePath = '';

  constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
    if (basePath) {
      this.basePath = basePath;
    }
    if (configuration) {
      this.configuration = configuration;
      this.basePath = basePath || configuration.basePath || this.basePath;
    }
  }

  /**
   * To generate a letter in iWrite
   * Generates a letter in iWrite for the details provided
   * @param generateLetter To generate a letter in iWrite
   * @param requestCorrelationId Initial Request GUID
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public generateLetter(generateLetter: GenerateLetterRequestVO, requestCorrelationId?: string, templateName?: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
  public generateLetter(generateLetter: GenerateLetterRequestVO, requestCorrelationId?: string, templateName?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
  public generateLetter(generateLetter: GenerateLetterRequestVO, requestCorrelationId?: string, templateName?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
  public generateLetter(generateLetter: GenerateLetterRequestVO, requestCorrelationId?: string, templateName?: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (generateLetter === null || generateLetter === undefined) {
      throw new Error('Required parameter generateLetter was null or undefined when calling generateLetter.');
    }

    let headers = this.defaultHeaders;
    if (requestCorrelationId !== undefined && requestCorrelationId !== null) {
      headers = headers.set('RequestCorrelationId', String(requestCorrelationId));
    }

    if (templateName !== undefined && templateName !== null) {
      headers = headers.set('CustomClaimLetterIndicator', String(templateName));
    }

    // authentication (OAuth2) required
    // oauth required
    if (this.configuration.accessToken) {
      const accessToken = typeof this.configuration.accessToken === 'function'
        ? this.configuration.accessToken()
        : this.configuration.accessToken;

      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }

    // to determine the Accept header
    const httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.post<any>(`${this.basePath}/api/letter/custom`,
      generateLetter,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * To search a letter in iWrite for a member
   * Provides a URL to search results in iWrite based on the AARP membership number
   * @param searchLetter To search a letter in iWrite
   * @param requestCorrelationId Initial Request GUID
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public searchLetter(searchLetter: SearchLetterRequestVO, requestCorrelationId?: string, observe?: 'body', reportProgress?: boolean): Observable<SearchLetterResponseVO>;
  public searchLetter(searchLetter: SearchLetterRequestVO, requestCorrelationId?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SearchLetterResponseVO>>;
  public searchLetter(searchLetter: SearchLetterRequestVO, requestCorrelationId?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SearchLetterResponseVO>>;
  public searchLetter(searchLetter: SearchLetterRequestVO, requestCorrelationId?: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (searchLetter === null || searchLetter === undefined) {
      throw new Error('Required parameter searchLetter was null or undefined when calling searchLetter.');
    }

    let headers = this.defaultHeaders;
    if (requestCorrelationId !== undefined && requestCorrelationId !== null) {
      headers = headers.set('RequestCorrelationId', String(requestCorrelationId));
    }

    // authentication (oauth) required
    if (this.configuration.accessToken) {
      const accessToken = typeof this.configuration.accessToken === 'function'
        ? this.configuration.accessToken()
        : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }

    // to determine the Accept header
    const httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.post<SearchLetterResponseVO>(`${this.basePath}/api/letter/search`,
      searchLetter,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = 'multipart/form-data';
    for (const consume of consumes) {
      if (form === consume) {
        return true;
      }
    }
    return false;
  }

}
