/**
 * MDM Mediator
 * This is the MDM Mediator REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: gabrielle_goodwin@uhc.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {AddressVO} from './AddressVO';
import {AuxiliaryPartyVO} from './AuxiliaryPartyVO';
import {InsuredPlanVO} from './InsuredPlanVO';
import {MdmMemberHeaderVO} from './MdmMemberHeaderVO';
import {MemberDetailsVO} from './MemberDetailsVO';

export class AccountMembershipResponseVO {
  memberDetails?: MemberDetailsVO;
  insuredPlan?: Array<InsuredPlanVO>;
  mdmMemHeaderDetails?: MdmMemberHeaderVO;
  auxiliaryParty?: Array<AuxiliaryPartyVO>;
  mailToAddress?: AddressVO;
  payToAddress?: AddressVO;
  fullName?: string;
  claimNumber?: string;
  claimNumberForUrl?: string;
}
