/**
 * MDM Mediator
 * This is the MDM Mediator REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: gabrielle_goodwin@uhc.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export class AddressVO {

  address?: AddressVO;

  addressLine1?: string;

  addressLine2?: string;

  city?: string;

  stateProvinceCode?: string;

  state?: string;

  postalCode?: string;

  countryCode?: string;

  countrySubCode?: string;

  startDt?: string;

  stopDt?: string;

}
