/**
 * MDM Mediator
 * This is the MDM Mediator REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: gabrielle_goodwin@uhc.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {AddressVO} from '../../bpm-mediator/model/AddressVO';
import {IdVO} from './IdVO';
import {NameVO} from './NameVO';
import {PhoneVO} from './PhoneVO';

export interface AuxiliaryPartyVO {
  auxiliaryPersonId?: string;
  auxiliaryPersonName?: NameVO;
  auxiliaryEntityName?: string;
  auxiliaryEntityType?: string;
  auxiliaryPersonType?: IdVO;
  auxiliaryPersonSource?: IdVO;
  documentReferenceNumber?: string;
  auxiliaryFulfillmentInd?: string;
  auxiliaryEmail?: string;
  auxiliaryEveningPhone?: PhoneVO;
  auxiliaryDayPhone?: PhoneVO;
  auxiliaryPersonPermAddress?: Array<AddressVO>;
  auxiliaryPersonTempAddress?: Array<AddressVO>;
  auxiliaryPersonRole?: Array<IdVO>;
  auxiliaryStartDate?: string;
  auxiliaryStopDate?: string;
}
