/**
 * MDM Mediator
 * This is the MDM Mediator REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: gabrielle_goodwin@uhc.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface MemberVO {
  lastName?: string;

  firstName?: string;

  middleName?: string;

  suffixName?: string;

  dateOfBirth?: string;

  gender?: string;

  partBDateEffective?: string;

  prefix?: string;

  dateOfDeath?: string;

  suffix?: string;

}
