/**
 * MDM Mediator
 * This is the MDM Mediator REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: gabrielle_goodwin@uhc.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {AddressVO} from '../../bpm-mediator/model/AddressVO';
import {MemberIdentifiersVO} from './MemberIdentifiersVO';
import {MemberVO} from '../../bpm-mediator/model/MemberVO';
import {MdmMemberHeaderVO} from './MdmMemberHeaderVO';

export interface ResourceOfSearchMemberVO {
  identifiers?: MemberIdentifiersVO;
  name?: MemberVO;
  mdmMemHeaderDetails?: MdmMemberHeaderVO;
  isActive?: boolean;
  permanentAddress?: AddressVO;
  temporaryAddress?: AddressVO;
  links?: { [key: string]: { [key: string]: string; }; };
}
