/**
 * MDM Mediator
 * This is the MDM Mediator REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: gabrielle_goodwin@uhc.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {AddressVO} from '../../bpm-mediator/model/AddressVO';
import {MemberIdentifiersVO} from './MemberIdentifiersVO';
import {MemberVO} from '../../bpm-mediator/model/MemberVO';
import {PolicyAsOfDosVO} from './PolicyAsOfDosVO';

export interface ResourceOfMemberProfileAsOfDosVO {
  member?: MemberVO;

  memberIdentifiers?: MemberIdentifiersVO;

  permanentAddress?: AddressVO;

  temporaryAddress?: AddressVO;

  levelSevenEditPolicyAsOfDosVo?: PolicyAsOfDosVO;

  /**
   * Service start date
   */
  asOfServiceDate?: Date;

  /**
   * Service end date, may be same as service date
   */
  asOfserviceEndDate?: Date;

  links?: { [key: string]: { [key: string]: string; }; };

}
