/**
 * MDM Mediator
 * This is the MDM Mediator REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: gabrielle_goodwin@uhc.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {AddressVO} from '../../bpm-mediator/model/AddressVO';
import {InsuredPlansVO} from './InsuredPlansVO';
import {MemberIdentifiersVO} from './MemberIdentifiersVO';
import {MemberVO} from '../../bpm-mediator/model/MemberVO';
import {PhoneVO} from './PhoneVO';

export class ResourceOfGetMemberVO {
  dateOfBirth?: string;
  emailAddress?: string;
  medicarePartBDate?: string;
  phoneNumbers?: Array<PhoneVO>;
  identifiers?: MemberIdentifiersVO;
  name?: MemberVO;
  permanentAddresses?: Array<AddressVO>;
  temporaryAddresses?: Array<AddressVO>;
  insuredPlans?: Array<InsuredPlansVO>;
  links?: { [key: string]: { [key: string]: string; }; };
}
