/**
 * MDM Mediator
 * This is the MDM Mediator REST API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {ProviderAddressVO} from './ProviderAddressVO';
import {ProviderNameVO} from './ProviderNameVO';

export interface ResourceOfPreferredAddressVO {
  providerName?: ProviderNameVO;
  preferredProviderAddress?: ProviderAddressVO;
  links?: { [key: string]: { [key: string]: string; }; };
}
