/**
 * MDM Mediator
 * This is the MDM Mediator REST API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {ProviderAddressVO} from './ProviderAddressVO';
import {ProviderNameVO} from './ProviderNameVO';
import {ProviderTinVO} from './ProviderTinVO';
import {SphCodeVO} from './SphCodeVO';
import {TaxDocumentationVO} from './TaxDocumentationVO';
import {TaxStatusVO} from './TaxStatusVO';

export interface TinInfoVO {
  tin?: ProviderTinVO;
  tinSpecialCode?: Array<SphCodeVO>;
  tinName?: ProviderNameVO;
  tinAddress?: ProviderAddressVO;
  tinTaxStatus?: Array<TaxStatusVO>;
  tinTaxDocumentation?: Array<TaxDocumentationVO>;
}
