/**
 * Model class WorkStorage
 * Path: screenbean/commqltyrvw
 * Model: com::uhc::aarp::fox::domain::screenbean::commQltyRvw::WorkStorage
 */
export class WorkStorage {
  s1 = 0;
  cnt = 0;
  s2 = 0;
  commLengthPacked = 0;
  commLength = 0;
  rbaFld = 0;
  filler5 = '';
  cnSeqNumeric = 0;
  filler14 = '';
  filler10 = '';
  altDate = '';
  browseRequest = '';
  altaSeq = 0;
  dateYymmdd = '';
  filler6 = '';
  commNumberNumeric = 0;
  lastStatus = '';
  filler12 = '';
  filler7 = '';
  lastQualNo = '';
  filler11 = '';
  lastReply = '';
  filler15 = '';
  cnDateNumeric = 0;
  altaLoc = 0;
  altSeq = '';
  filler8 = '';
  cnDate = '';
  statusError = '';
  dateMmddyy = '';
  filler9 = '';
  qnDate = '';
  qnLoc = '';
  suspenError = '';
  altLoc = 0;
  lastCommNo = '';
  qnSeq = '';
  pacsId = 0;
  filler1 = '';
  screenError = '';
  qnDateNumeric = 0;
  commandEnteredInd = '';
  qnLocNumeric = 0;
  altaDate = 0;
  filler13 = '';
  altDateNumeric = 0;
  qnSeqNumeric = 0;
  cnSeq = '';
  wlastComm = '';
  browseEndLocation = '';
  filler16 = '';
  altSeqNumeric = 0;
  wsLocSiteCheck = '';
  firstComm = '';
  nextComm = '';
}
