import {ClaimNumberFile, CommComm, Oprec1Record, QualityCommAreaFieldsFor06o75, QualityReviewRecord} from '@fox/shared';

/*import { OperatorStatsRecordPO } from '../../common/pos/operator-stats-record-po.model';*/

/**
 * Model class WorkArea
 * Path: screenbean/qltyrvwrvldmenu
 * Model: com::uhc::aarp::fox::domain::screenbean::qltyRvwRvldMenu::WorkArea
 * Legacy Mapping: WORK-AREA
 */
export class WorkArea {
  userId = 0;
  userIdComp = 0;
  sub = 0;
  null1 = '';
  inv = 0;
  commLength = 0;
  commandCommLength = 0;
  oprecLength = 0;
  claimIndexLength = 0;
  claimLength = 0;
  rbaFld = 0;
  queLength = 0;
  queItem = 0;
  cnt = 0;
  queLengthPacked = 0;
  startTime = 0;
  endTime = 0;
  elapseTime = 0;
  pgmComm = '';
  queTerminal = '';
  csCommComm = new CommComm();
  csCommand = '';
  csProcessingInd = '';
  csRevalDisbPct = '';
  csRevalSuspPct = '';
  csLastReply = '';
  csLastClmNo = '';
  csLastQualNo = '';
  csEibTime = 0;
  csTotalReviewed = '';
  csTotalSuspended = '';
  csRevalOverpymt = 0;
  commandEnteredInd = '';
  wionsId = '';
  wionsIdNumeric = 0;
  wsIonsIdComp = 0;
  wsIonsIdSave = 0;
  journalId = '';
  jfMembNo = '';
  jfAssoc = '';
  jfInsCode = '';
  jfClaimNo = '';
  pacsId = 0;
  pacsMemNo = '';
  pacsAssoc = '';
  pacsInsCode = '';
  eibTime = 0;
  eibHours = 0;
  eibMinutes = 0;
  eibSeconds = 0;
  claimNumber = '';
  qnDateMm = '';
  qnDateDd = '';
  qnDateYy = '';
  qnLoc = '';
  qnLocNum = 0;
  qnSeq = '';
  qnIonsId = '';
  qnIonsIdNumeric = 0;
  altLoc = 0;
  altDateYy = '';
  altDateMm = '';
  altDateDd = '';
  altSeqNumeric = 0;
  altsLoc = 0;
  altsDateYy = '';
  altsDateMm = '';
  altsDateDd = '';
  altsSeq = 0;
  qualLoc = 0;
  qualDate = 0;
  qualSeq = 0;
  qualityKeySave = '';
  qualHighLoc = 0;
  qualHighDate = 0;
  qualHighSeq = 0;
  qualityHighKeySave = '';
  endOfIonsInd = '';
  browseRequest = '';
  lastSuspenseReason = '';
  commaInd = '';
  screenError = '';
  browseEndLocation = '';
  stYy = 0;
  stMm = 0;
  stDd = 0;
  statisticsDateRedef = 0;
  cdMm = '';
  cdDd = '';
  cdYy = '';
  enterLits = '';
  lastReply = '';
  lastClmNo = '';
  lastQualNo = '';
  qualEmpId = '';
  clmEmpId = '';
  claimIonsId = 0;
  qualIonsId = 0;
  operatorStatsRecord: any;
  qualityCommAreaFieldsFor06o75 = new QualityCommAreaFieldsFor06o75();
  binNumFunc = 0;
  binNumRcode = 0;
  claimKsds = 0;
  claimRrds = 0;
  rcErrorByte = '';
  holdByte = 0;
  holdRByte = 0;
  binNumHighByte = 0;
  y2kDate1 = new Date();
  y2kDate2 = new Date();
  y2kLoc1 = 0;
  y2kLoc2 = 0;
  y2kSeq2 = 0;
  y2kSeq1 = 0;
  cnYr = '';
  cnSplit = '';
  cnCart = '';
  cnLoc = '';
  cnDay = '';
  cnSeq = '';
  cnLocNum = 0;
  enterErrors = [];
  qualityReviewRecord = new QualityReviewRecord();
  oprec1Record = new Oprec1Record();
  claimNumberFile = new ClaimNumberFile();
  stopProcessing = false;
  qualityInfoRecord: any;

}
