/**
 * fox-claims-finance
 * Custom developed service operations to support claim financial processing, such as payment, deposit, and TRC processing.  Services interact with modernized code.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {AddressVO} from '../../bpm-mediator/model/AddressVO';
import {InstituteEnum} from '../enums/institute.enum';
import {ActionRequestReasonEnum} from '../enums/action-request-reason.enum';

export interface CheckReplaceVO {
    checkIds?: Array<number>;
    institute?: InstituteEnum;
    payeeEntireName?: string;
    payeeSurname?: string;
    payeeFirstName?: string;
    payeeMiddleInit?: string;
    suffix?: string;
    actionRequestReason?: ActionRequestReasonEnum;
    actionReasonOtherDesc?: string;
    tin?: number;
    npi?: number;
    payeeAddress?: AddressVO;
    notation?: string;
    printNotationOnCheck?: boolean;
    returned?: boolean;
}
