import {CheckActionDetailVO} from './CheckActionDetailVO';
/**
 * payment-reconciliation
 * Services to support Payment Reconciliation screen consolidation
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {PayeeAddressVO} from './PayeeAddressVO';

export class ResourceOfCheckVO {
  checkId?: number;

  checkSeries?: string;

  checkNumber?: number;

  checkAmount?: number;

  isBulk?: boolean;

  issueDate?: string;

  status?: CheckStatusEnum;

  payee?: string;

  payeeFirstName?: string;

  payeeMiddleInitial?: string;

  payeeSurname?: string;

  suffix?: string;

  payeeAddress?: PayeeAddressVO;

  tin?: number;

  npi?: number;

  claimAmount?: number;

  claimNumber?: string;

  accountNumber?: string;

  insuredName?: string;

  cashAmount?: number;

  buwIndicator?: string;

  complete?: string;

  cashDate?: string;

  paypointCode?: string;

  checkActionDetail?: CheckActionDetailVO;

  _links?: { [key: string]: { [key: string]: string; }; };

}

export enum CheckStatusEnum {
  OUTSTANDING = 'OUTSTANDING',
  PAID = 'PAID',
  VOID = 'VOID',
  REPLACED = 'REPLACED',
  VOID_REQUESTED = 'VOID_REQUESTED',
  REPLACEMENT_REQUESTED = 'REPLACEMENT_REQUESTED',
  VOID_AUTHORIZED = 'VOID_AUTHORIZED',
  REPLACEMENT_AUTHORIZED = 'REPLACEMENT_AUTHORIZED',
  REPLACEMENT_PENDING = 'REPLACEMENT_PENDING',
  UNCLAIMED_FUNDS = 'UNCLAIMED_FUNDS',
  NO_STATUS = 'NO_STATUS'
}
