/**
 * payment-reconciliation
 * Services to support Payment Reconciliation screen consolidation
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export class ResourceOfPurgeCheckVO {
  purgeId?: number;

  issueDate?: string;

  checkSeries?: string;

  checkNumber?: number;

  claimBatchNumber?: string;

  associatedAccountNumber?: number;

  status: ResourceOfPurgeCheckVO.StatusEnum = ResourceOfPurgeCheckVO.StatusEnum.NOSTATUS;

  purgeDate?: string;

  cashDate?: string;

  checkAmount?: number;

  isBulk?: boolean;

  links?: { [key: string]: { [key: string]: string; }; };

}

export namespace ResourceOfPurgeCheckVO {
  export enum StatusEnum {
    OUTSTANDING = 'OUTSTANDING',
    PAID = 'PAID',
    VOID = 'VOID',
    REPLACED = 'REPLACED',
    VOIDREQUESTED = 'VOID_REQUESTED',
    REPLACEMENTREQUESTED = 'REPLACEMENT_REQUESTED',
    VOIDAUTHORIZED = 'VOID_AUTHORIZED',
    REPLACEMENTAUTHORIZED = 'REPLACEMENT_AUTHORIZED',
    REPLACEMENTPENDING = 'REPLACEMENT_PENDING',
    UNCLAIMEDFUNDS = 'UNCLAIMED_FUNDS',
    NOSTATUS = 'NO_STATUS'
  }
}
