import { TempSortLine } from './temp-sort-line.model';
import { TempStaff2 } from './temp-staff2.model';
import { WsHoldForColon } from './ws-hold-for-colon.model';

/**
 * Model class WorkStorage
 * Path: screenbean/qltyrvwoperstat
 * Model: com::uhc::aarp::fox::domain::screenbean::qltyrvwoperstat::WorkStorage
 * Legacy Mapping: PROGRAM-WORK-AREAS
 */
export class WorkStorage {
  returnLength = 0;
  workDate = 0;
  screenDate = '';
  wsCumDate = '';
  tempTimeA = 0;
  tempTime1 = 0;
  tempTime = '';
  tempTimeB = 0;
  tempTime2 = '';
  totalMin = 0;
  compTime = 0;
  compTime2 = 0;
  tempTimeZ = 0;
  tempTime4 = 0;
  tempTime5 = '';
  tempTime6 = 0;
  tempTime7 = 0;
  tempStaffA = 0;
  tempStaff1 = 0;
  tempStaffB = 0;
  tempStaff2 = new TempStaff2();
  compStaff = 0;
  compStaff2 = 0;
  tempStaffZ = 0;
  tempStaff4 = 0;
  tempStaff5 = '';
  tempStaff6 = 0;
  tempStaff7 = 0;
  tempNewStaffs: number[] = [];
  totalHours = 0;
  averageQual = 0;
  clDate = 0;
  clIonsId = 0;
  cuDate = 0;
  cuRecordType = 0;
  cuSite = 0;
  cuDivision = 0;
  cuLocation = 0;
  cuIons = 0;
  tempHours3 = 0;
  point3 = '';
  tempMin3 = 0;
  screenNums: number[] = [];
  tempWhole = 0;
  tempHalf = 0;
  tempWhole3 = 0;
  staffPoint = '';
  tempHalf3 = 0;
  screenStaffs: number[] = [];
  ws99CommandCommarea = '';
  beginDate99 = 0;
  endDate99 = 0;
  returnMess99 = '';
  workField2 = 0;
  tempSortLine = new TempSortLine();
  wsHoldForColon = new WsHoldForColon();
  locTotTempHours = 0;
  temporaryTime = '';
  tempTotalHours = 0;
  tempLocAvgHrHold = 0;
  tempLocAvgHr = 0;
  minutesInHours = 0;
  wsHoursForMapR = 0;
  wsHoursForMap = '';
  avgTempTime = 0;
  avgTotalHours = 0;
  staffCntr = 0;
  cntr = 0;
  cntr2 = 0;
  sub1 = 0;
  sub2 = 0;
  sub3 = 0;
  tempCntr = 0;
  colonCtr = 0;
  subAmount = 0;
  sortCtr1 = 0;
  sortSub1 = 0;
  sortCtr2 = 0;
  sortSub2 = 0;
  sortSub3 = 0;
  wsLocTotRevd = 0;
  wsLocTotSuspd = 0;
  wsLocTotRemvd = 0;
  wsLocTotChanged = 0;
  wsLocTotExpressed = 0;
  wsLocTotRemOSus = 0;
  wsLocTotPercSus = 0;
  wsValidReviewInd = '';
  commandEnteredInd = '';
  pf3Entered = '';
  pf4Entered = '';
  tempNumeric = 0;
  tempLoc = 0;
  wsRecCount = 0;
  maxLines = 0;
  wsCount = 0;
  recordKeyAlpha = '';
  tempScreen = 0;
  avgQualPartOne = 0;
  avgQualPartTwo = 0;
  avgQualPerMin = 0;
  pfMessagePart1 = '';
  pfMessagePart2 = '';
  commandCommLen = 0;
  comp18 = 0;
  tempHalf4 = 0;
}
