/**
 * compas-mediator
 * The proxy service between FOX services and COMPAS that is required to facilitate member plan eligibility and benefit modification information
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BenModVO } from './BenModVO';

export interface PlanVO {
    planCode?: string;
    planName?: string;
    status?: string;
    effectiveDate?: string;
    termDate?: string;
    reasonForTerm?: string;
    benMod?: Array<BenModVO>;
}
