import {OperatorFileOfAuthLimitPlansPO} from './operator-file-of-auth-limit-plans-po.model';
import {OperatorFileOfAuthorityLimitCombosPO} from './operator-file-of-authority-limit-combos-po.model';
import {OperatorFileOfCautionsPO} from './operator-file-of-cautions-po.model';
import {OperatorFileOfOverrideAuthCautionsPO} from './operator-file-of-override-auth-cautions-po.model';
import {OperatorFileOfOverrideSqCautionsPO} from './operator-file-of-override-sq-cautions-po.model';
import {OperatorFileOfOverrideSqLettersPO} from './operator-file-of-override-sq-letters-po.model';
import {OperatorFileOfOverrideSqMessagesPO} from './operator-file-of-override-sq-messages-po.model';
import {OperatorFileOfsqCautionsPO} from './operator-file-ofsq-cautions-po.model';
import {OperatorFileOfsqLetterTypesPO} from './operator-file-ofsq-letter-types-po.model';
import {OperatorFileOfsqMessagePO} from './operator-file-ofsq-message-po.model';
import {OperatorFileOfsqSetQualityCombosPO} from './operator-file-ofsq-set-quality-combos-po.model';

/**
 * Model class OperatorFilePO
 * Path: common/pos
 * Model: com::uhc::aarp::fox::domain::common::entities::OperatorFile
 */
export class OperatorFilePO {
  operFlId = 0;
  ionsId = 0;
  lstNm = '';
  fstNm = '';
  authLvl = 0;
  pstn = '';
  loc = 0;
  actulLvl = 0;
  titl = '';
  fullTm = '';
  elevQ = '';
  schl = '';
  socSecNbr = 0;
  operApptDt = new Date();
  operTermDt = new Date();
  operInfoMaintDt = new Date();
  operInfoMaintIons = 0;
  othr = '';
  operAuthMaintDt = new Date();
  operAuthMaintIons = 0;
  operProcDt = new Date();
  dcsdInsd = '';
  xcptScr = '';
  fgnProv = '';
  payAdj = '';
  waivPrem = '';
  medsuppLtrXhst = '';
  allPlnInd = '';
  clmAggr = 0;
  prdOfStay = 0;
  snfCnfn = 0;
  pdnFstPay = '';
  pdnShft = 0;
  pdnUAndPBen = 0;
  setqMaintDt = new Date();
  setqMaintIons = 0;
  qAdminAddrPct = 0;
  qPayToSpecPaye = 0;
  qCorp = 0;
  qPay = 0;
  qNonPay = 0;
  qSpecMemo = 0;
  qNewDctr = 0;
  qNewHosp = 0;
  qSpltClm = 0;
  qBenExt = 0;
  qPdn1StPay = 0;
  qAsdHospPayPct = 0;
  qAsdHospPayAmt = 0;
  qAsdPayPct = 0;
  qAsdPayAmt = 0;
  qNonAsdInhospPayPct = 0;
  qNonAsdInhospPayAmt = 0;
  qNonAsdPayPct = 0;
  qNonAsdPayAmt = 0;
  qXcptScr = 0;
  qLtrPct = 0;
  qCommPct = 0;
  qRevalDisbPct = 0;
  qRevalSuspPct = 0;
  qRevalAmt = 0;
  qDcsdInsPct = 0;
  qPayAdj = 0;
  qMedsuppLtrExhPct = 0;
  tranSecurMaintDt = new Date();
  tranSecurMaintIons = 0;
  procClm = '';
  qltyRev = '';
  refAprv = '';
  operStats = '';
  clmNoAsgn = '';
  rslvClmNo = '';
  eobRepl = '';
  noteCommXrefNo = '';
  trnsf = '';
  yrDedAggr = '';
  altaddPayeDecDt = '';
  vipAcss = '';
  crosRefNbr = '';
  eobMnt = '';
  specHandCd = '';
  delOvPay = '';
  reactivateClm = '';
  delClmNo = '';
  qltyRevalidation = '';
  qltyInfo = '';
  qltyVol = '';
  qltyErrInq = '';
  unrevQltyMicReq = '';
  ovpay = '';
  icdDesc = '';
  ltrWthAcct = '';
  commInfo = '';
  microfilmReq = '';
  commDel = '';
  reprint = '';
  refToIonsChg = '';
  microfilmReqPrt = '';
  ltrLib = '';
  commLtrQualRev = '';
  ltrWoAcct = '';
  microfilmRng = '';
  hlpFl = '';
  operFl = '';
  operAuthLmt = '';
  operTransSecur = '';
  operSetQlty = '';
  dfltAuthLmt = '';
  dfltTransSecur = '';
  dfltSetQlty = '';
  ovrdAuthLmt = '';
  ovrdSetQlty = '';
  provFl = '';
  provQlty = '';
  msgFl = '';
  msgQlty = '';
  titls = '';
  ecRejMaint = '';
  ecSuspProc = '';
  ecCarrConv = '';
  ecCtl = '';
  hicNbr = '';
  hicAcfInd = '';
  setVqrPctAny = 0;
  setVqrPct2OrMore = 0;
  operatorFileOfAuthLimitPlanss: OperatorFileOfAuthLimitPlansPO[] = [];
  operatorFileOfsqLetterTypess: OperatorFileOfsqLetterTypesPO[] = [];
  operatorFileOfAuthorityLimitComboss: OperatorFileOfAuthorityLimitCombosPO[] = [];
  operatorFileOfsqMessages: OperatorFileOfsqMessagePO[] = [];
  operatorFileOfsqCautionss: OperatorFileOfsqCautionsPO[] = [];
  operatorFileOfsqSetQualityComboss: OperatorFileOfsqSetQualityCombosPO[] = [];
  operatorFileOfOverrideSqMessagess: OperatorFileOfOverrideSqMessagesPO[] = [];
  operatorFileOfOverrideSqCautionss: OperatorFileOfOverrideSqCautionsPO[] = [];
  operatorFileOfOverrideSqLetterss: OperatorFileOfOverrideSqLettersPO[] = [];
  operatorFileOfOverrideAuthCautionss: OperatorFileOfOverrideAuthCautionsPO[] = [];
  operatorFileOfCautionss: OperatorFileOfCautionsPO[] = [];
}
