/**
 * fox-claims
 * Custom developed service operations to support core claim processing and claim history inquiry.  Some services interact with modernized code.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface AggregatesVO {
    plan?: string;
    outOfPocket?: string;
    aarpPartBDeductible?: string;
    deductibleCarryover?: string;
    foreignDeductible?: string;
    drugDeductible?: string;
    medicareDeductibleRefund?: string;
    lifeForeignAggregate?: string;
    lifeHospitalDays?: string;
    benefitPeriodLifetimeAggregate?: string;
    lifetimeMentalAggregate?: string;
    erObservationVisitsAggregate?: string;
    drugBenefitAggregate?: string;
    hospitalLifetimeAggregate?: string;
    lifetimeBenefitAggregate?: string;
    healthcareVisits?: string;
    nursingHomeAggregate?: string;
    preventiveCareAggregate?: string;
    visitsAggregate?: string;
    yearlyMentalAggregate?: string;
    homeHealthcareAggregate?: string;
    yearlyHomeHealthcareAggregate?: string;
    outpatientHospitalAggregate?: string;
    planBenefitAggregate?: string;
    fiftyDollarDeductible?: string;
    fiveVisitDeductible?: string;
    twentyFiveDollarDeductible?: string;
    medicalDeductible?: string;
}
