/**
 * fox-claims
 * Monolithic-style application containing generated components from legacy code modernization and custom developed APIs to support core claim processing.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ClaimMemberVO {
  claimMemberId?: number;

  firstName?: string;

  lastName?: string;

  middleName?: string;

  suffix?: string;

  aarpMembershipNumber?: string;

  medicareBeneficiaryId?: string;

  dateOfBirth?: Date;

  dateOfDeath?: Date;

  addressLine1?: string;

  addressLine2?: string;

  city?: string;

  state?: string;

  zip?: string;

  country?: string;

  memberMasterRecordNumber?: number;

}
