/**
 * fox-claims
 * Monolithic-style application containing generated components from legacy code modernization and custom developed APIs to support core claim processing.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ClaimHistorySendReplaceEobRaEligibleVO {
  sendReplaceEobEligible?: ClaimHistorySendReplaceEobRaEligibleVO.SendReplaceEobEligibleEnum;
  sendReplaceRaEligible?: ClaimHistorySendReplaceEobRaEligibleVO.SendReplaceRaEligibleEnum;
  sendReplaceIndicator?: ClaimHistorySendReplaceEobRaEligibleVO.SendReplaceIndicatorEnum;
  claimNumber?: number;
  claimDosFromDate?: string;
  claimDosToDate?: string;
  claimHistoryStatus?: string;
  primaryIcdCode?: string;
  claimTypeIndicator?: string;
}

export namespace ClaimHistorySendReplaceEobRaEligibleVO {
  export type SendReplaceEobEligibleEnum = 'Y' | 'N';
  export const SendReplaceEobEligibleEnum = {
    Y: 'Y' as SendReplaceEobEligibleEnum,
    N: 'N' as SendReplaceEobEligibleEnum
  };
  export type SendReplaceRaEligibleEnum = 'Y' | 'N';
  export const SendReplaceRaEligibleEnum = {
    Y: 'Y' as SendReplaceRaEligibleEnum,
    N: 'N' as SendReplaceRaEligibleEnum
  };
  export type SendReplaceIndicatorEnum = 'SEND' | 'REPLACE';
  export const SendReplaceIndicatorEnum = {
    SEND: 'SEND' as SendReplaceIndicatorEnum,
    REPLACE: 'REPLACE' as SendReplaceIndicatorEnum
  };
}
