/**
 * fox-claims
 * Custom developed service operations to support core claim processing and claim history inquiry.  Some services interact with modernized code.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ClaimHistMaintRequestUpdateVO {
  maintRequestId?: string;
  actionType?: ClaimHistMaintRequestUpdateVO.ActionTypeEnum;
  requestStatus?: ClaimHistMaintRequestUpdateVO.RequestStatusEnum;
  maintRequestUpdateDesc?: string;
}
export namespace ClaimHistMaintRequestUpdateVO {
  export type ActionTypeEnum = 'DELETECLAIM' | 'TRANSFERCLAIM' | 'UPDATEEOB' | 'CROSSREFMAINT' | 'MEMBERAGGRMAINT' | 'SPHMAINT' | 'ACCOUNTTRANSFER' | 'REACTIVATECLAIM';
  export const ActionTypeEnum = {
    DELETECLAIM: 'DELETECLAIM' as ActionTypeEnum,
    TRANSFERCLAIM: 'TRANSFERCLAIM' as ActionTypeEnum,
    UPDATEEOB: 'UPDATEEOB' as ActionTypeEnum,
    CROSSREFMAINT: 'CROSSREFMAINT' as ActionTypeEnum,
    MEMBERAGGRMAINT: 'MEMBERAGGRMAINT' as ActionTypeEnum,
    SPHMAINT: 'SPHMAINT' as ActionTypeEnum,
    ACCOUNTTRANSFER: 'ACCOUNTTRANSFER' as ActionTypeEnum,
    REACTIVATECLAIM: 'REACTIVATECLAIM' as ActionTypeEnum
  };
  export type RequestStatusEnum = 'APPROVED' | 'DENIED';
  export const RequestStatusEnum = {
    APPROVED: 'APPROVED' as RequestStatusEnum,
    DENIED: 'DENIED' as RequestStatusEnum
  };
}
