import {ClaimMemberVO} from './ClaimMemberVO';
import {ClaimStatusVO} from './ClaimStatusVO';
import {ProviderVO} from './ProviderVO';
import {ServiceLineVO} from './ServiceLineVO';

/**
 * fox-claims
 * Monolithic-style application containing generated components from legacy code modernization and custom developed APIs to support core claim processing.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export interface ClaimVO {
  claimId?: number;

  preProcessingSystemClaimId: string;

  preProcessingSystem: string;

  legacyClaimNumber?: string;

  claimReceiptDate?: Date;

  serviceLines: Array<ServiceLineVO>;

  claimProviders: Array<ProviderVO>;

  claimMember: ClaimMemberVO;

  claimStatus: ClaimStatusVO;

}
