/**
 * fox-claims
 * Custom developed service operations to support core claim processing and claim history inquiry.  Some services interact with modernized code.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CombinedClaimVO } from './CombinedClaimVO';

export interface PagedResourcesofCombinedClaimVO {
    numOfCombinedClaims?: number;
    sendDate?: string;
    combinedClaimType?: PagedResourcesofCombinedClaimVO.CombinedClaimTypeEnum;
    items?: CombinedClaimVO;
    links?: { [key: string]: { [key: string]: string; }; };
}

export namespace PagedResourcesofCombinedClaimVO {
    export type CombinedClaimTypeEnum = 'INSURED' | 'PROVIDER';
    export const CombinedClaimTypeEnum = {
        INSURED: 'INSURED' as CombinedClaimTypeEnum,
        PROVIDER: 'PROVIDER' as CombinedClaimTypeEnum
    };
}
