/**
 * fox-pre-adjudication
 * Orchestrates the pre-adjudication process, supporting both auto and manual processing of claims through provider validation.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NameVO } from '../../mdm-mediator/model/NameVO';
import { ProviderAddressVO } from '../../mdm-mediator/model/ProviderAddressVO';
import { ProviderIdentifierVO } from './ProviderIdentifierVO';

export interface ProviderValidationManualRequestVO {
  providerName?: NameVO;
  providerAddress?: ProviderAddressVO;
  providerIdentifier?: ProviderIdentifierVO;
  phoneNumber?: string;
  phoneExt?: string;
  fax?: string;
  email?: string;
  taxonomyCode?: string;
  providerType?: ProviderValidationManualRequestVO.ProviderTypeEnum;
  providerClaimAssignment?: boolean;
}
export namespace ProviderValidationManualRequestVO {
  export type ProviderTypeEnum = 'I' | 'O' | 'M';
  export const ProviderTypeEnum = {
    I: 'I' as ProviderTypeEnum,
    O: 'O' as ProviderTypeEnum,
    M: 'M' as ProviderTypeEnum
  };
}
