import {DupCheckDupBillLineVO} from './DupCheckDupBillLineVO';
/**
 * fox-claims
 * Custom developed service operations to support core claim processing and claim history inquiry.  Some services interact with modernized code.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ResourceOfDupCheckVO {
  duplicateIndicator?: ResourceOfDupCheckVO.DupIndicatorEnum;
  chargeLineKey?: string;
  chargeLineType?: string;
  duplicateBillLines?: Array<DupCheckDupBillLineVO>;
  possibleDuplicateBillLines: string[];
  notDuplicateBillLines: string[];
    links?: { [key: string]: { [key: string]: string; }; };
}
export namespace ResourceOfDupCheckVO {
    export type DupIndicatorEnum = 'Possible' | 'Duplicate' | 'NotDuplicate';
    export const DupIndicatorEnum = {
        POSSIBLE: 'POSSIBLE' as DupIndicatorEnum,
        DUPLICATE: 'DUPLICATE' as DupIndicatorEnum,
        NOTDUPLICATE: 'NOTDUPLICATE' as DupIndicatorEnum
    };
}
