/**
 * fox-claims
 * Custom developed service operations to support core claim processing and claim history inquiry.  Some services interact with modernized code.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ResourceOfLineDetailVO {
    lineKey?: string;
    lineType?: string;
    rxDosFromDt?: string;
    rxDosToDt?: string;
    rxChargeAmt?: string;
    rxNdcNum?: string;
    clmIcn?: string;
    profDosFromDt?: string;
    profDosToDt?: string;
    profChargeAmt?: string;
    profCoinsAmt?: string;
    profMcareDedAmt?: string;
    profCptCd?: string;
    profModCd1?: string;
    profModCd2?: string;
    profModCd3?: string;
    profModCd4?: string;
    hospDosFromDt?: string;
    hospDosToDt?: string;
    hospFacilityCd?: string;
    hospFrequencyCd?: string;
    hospMcareHospDays2?: string;
    hospMcareHspIhd?: string;
    claimNum?: string;
    links?: { [key: string]: { [key: string]: string; }; };
}
