/**
 * fox-claims
 * Monolithic-style application containing generated components from legacy code modernization and custom developed APIs to support core claim processing.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ResourceOfDepositSummaryVO {
  depositSummaryId?: number;
  depositCount?: number;
  depositSummaryTotal?: string;
  depositSource?: string;
  depositDateReceived?: string;
  depositSummaryStatus?: string;
  despositSummaryStatusReason?: string;
  verifiedBy?: string;
  verifiedDate?: Date;
  links?: { [key: string]: { [key: string]: string; }; };
}
