/**
 * fox-claims
 * Custom developed service operations to support core claim processing and claim history inquiry.  Some services interact with modernized code.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ResourceOfClaimHistMaintHistVO {
  maintAction?: ResourceOfClaimHistMaintHistVO.MaintActionEnum;
  requestTimestamp?: string;
  aarpMembershipNumber?: string;
  claimNumber?: string;
  requestStatus?: ResourceOfClaimHistMaintHistVO.RequestStatusEnum;
  requesterMsid?: string;
  approverMsid?: string;
  maintRequestId?: string;
  teamLocCd?: string;
  transCd?: string;
  chKey?: string;
  chAcctPartNum?: string;
  acctInfoKey?: string;
  chAcctPartNbr?: string;
  maintTypeDescription?: string;
  reviewedTimestamp?: string;
  maintRequestUpdateDesc?: string;

  links?: { [key: string]: { [key: string]: string; }; };
}
export namespace ResourceOfClaimHistMaintHistVO {
  export type MaintActionEnum = 'DELETECLAIM' | 'TRANSFERCLAIM' | 'UPDATEEOB' | 'CROSSREFMAINT' | 'MEMBERAGGRMAINT' | 'SPHMAINT' | 'ACCOUNTTRANSFER' | 'REACTIVATECLAIM';
  export const MaintActionEnum = {
    DELETECLAIM: 'DELETECLAIM' as MaintActionEnum,
    TRANSFERCLAIM: 'TRANSFERCLAIM' as MaintActionEnum,
    UPDATEEOB: 'UPDATEEOB' as MaintActionEnum,
    CROSSREFMAINT: 'CROSSREFMAINT' as MaintActionEnum,
    MEMBERAGGRMAINT: 'MEMBERAGGRMAINT' as MaintActionEnum,
    SPHMAINT: 'SPHMAINT' as MaintActionEnum,
    ACCOUNTTRANSFER: 'ACCOUNTTRANSFER' as MaintActionEnum,
    REACTIVATECLAIM: 'REACTIVATECLAIM' as MaintActionEnum
  };
  export type RequestStatusEnum = 'PENDING' | 'APPROVED' | 'DENIED';
  export const RequestStatusEnum = {
    PENDING: 'PENDING' as RequestStatusEnum,
    APPROVED: 'APPROVED' as RequestStatusEnum,
    DENIED: 'DENIED' as RequestStatusEnum
  };
}
