/**
 * fox-claims
 * Monolithic-style application containing generated components from legacy code modernization and custom developed APIs to support core claim processing.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {ClaimHistoryMemberVO} from './ClaimHistoryMemberVO';

export interface ResourceOfClaimHistoryVO {
  claimHistoryMember?: ClaimHistoryMemberVO;
  claimNumber?: string;
  claimId?: number;
  claimDosFromDate?: string;
  claimDosToDate?: string;
  billProviderNPI?: string;
  billProviderFirstName?: string;
  billProviderLastName?: string;
  billProviderBusName?: string;
  claimHistoryStatus?: string;
  claimHistoryStatusCode?: string;
  claimHistoryStatusDescription?: string;
  planType?: string;
  planTypeDescription?: string;
  amtPlanPaid?: string;
  assignedIndicator?: string;
  combinedStatusIndicator?: string;
  combinedStatusIndicatorDescription?: string;
  noPayIndicator?: string;
  eobType?: string;
  numOfBillLines?: string;
  links?: { [key: string]: { [key: string]: string; }; };
}

export namespace ResourceOfClaimHistoryVO {
  export type ClaimHistoryStatusEnum =
    'DISBURSED'
    | 'SUSPENDED'
    | 'DELETED'
    | 'POINT OF SALE DRUG CLAIM'
    | 'AWAITING QUALITY REVIEW';
  export const ClaimHistoryStatusEnum = {
    DISBURSED: 'DISBURSED' as ClaimHistoryStatusEnum,
    SUSPENDED: 'SUSPENDED' as ClaimHistoryStatusEnum,
    DELETED: 'DELETED' as ClaimHistoryStatusEnum,
    POINTOFSALEDRUGCLAIM: 'POINT OF SALE DRUG CLAIM' as ClaimHistoryStatusEnum,
    AWAITINGQUALITYREVIEW: 'AWAITING QUALITY REVIEW' as ClaimHistoryStatusEnum
  };
}
