/**
 * fox-claims
 * Monolithic-style application containing generated components from legacy code modernization and custom developed APIs to support core claim processing.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ResourceOfClaimBillLineDetailsVO {
  eobBillLineNumber?: string;
  eobPlanCode?: string;
  eobTypeOfService?: string;
  eobRenderingProv?: string;
  eobPharmacyType?: string;
  eobDosFromDate?: string;
  eobDosToDate?: string;
  eobChargeAmt?: string;
  eobNdc?: string;
  eobRxNum?: string;
  eobRxName?: string;
  eobAllowedAmt?: string;
  eobCoveredExpenseAmt?: string;
  eobDeductAmt?: string;
  eobBenefitAmt?: string;
  eobNoPay?: string;
  eobPreExisting?: string;
  eobBillingProvName?: string;
  eobBillingProvNpi?: string;
  enteredBillLineNumber?: string;
  enteredPlanCode?: string;
  enteredTypeOfService?: string;
  enteredRenderingProvider?: string;
  enteredPharmacyType?: string;
  enteredDosFromDate?: string;
  enteredDosToDate?: string;
  enteredChargeAmt?: string;
  enteredNdc?: string;
  enteredRxNum?: string;
  enteredRxName?: string;
  enteredAllowedAmt?: string;
  enteredCoveredExpenseAmt?: string;
  enteredDeductAmt?: string;
  enteredBenefitAmt?: string;
  enteredNoPay?: string;
  enteredPreExisting?: string;
  enteredBillingProvName?: string;
  enteredBillingProvNpi?: string;
  eobRenderingProvNpi?: string;
  eobCpt?: string;
  eobCptModifier1?: string;
  eobCptModifier2?: string;
  eobCptModifier3?: string;
  eobCptModifier4?: string;
  enteredRenderingProvNpi?: string;
  enteredCpt?: string;
  enteredCptModifier1?: string;
  enteredCptModifier2?: string;
  enteredCptModifier3?: string;
  enteredCptModifier4?: string;
  eobMedicareApprvdAmt?: string;
  eobMedicarePaidAmt?: string;
  eobMedicareDeductAmt?: string;
  eobCoinsAmt?: string;
  eobCopay?: string;
  eobMedicareAssgnInd?: string;
  eobPercentPaid?: string;
  eobExclPaymentPlan?: string;
  enteredMedicareApprvdAmt?: string;
  enteredMedicarePaidAmt?: string;
  enteredMedicareDeductAmt?: string;
  enteredCoinsAmt?: string;
  enteredCopay?: string;
  enteredMedicareAssgnInd?: string;
  enteredPercentPaid?: string;
  enteredExclPaymentPlan?: string;
  eobNumOfShifts?: string;
  eobNumOfNrsHours?: string;
  eobEligCharge?: string;
  eobRevenueCode?: string;
  eobNumOfDays?: string;
  eobNumOfIcuDays?: string;
  eobDateOfSurgery?: string;
  eobMedicareInpatientDeductInd?: string;
  eobMedicareLtr?: string;
  eobSnfDays?: string;
  eobSnfCoinDays?: string;
  eobSnfGreaterThan100?: string;
  eobDateOfAccident?: string;
  enteredNumOfShifts?: string;
  enteredNumOfNrsHours?: string;
  enteredEligCharge?: string;
  enteredRevenueCode?: string;
  enteredNumOfDays?: string;
  enteredNumOfIcuDays?: string;
  enteredDateOfSurgery?: string;
  enteredMedicareInpatientDeductInd?: string;
  enteredMedicareLtr?: string;
  enteredSnfDays?: string;
  enteredSnfCoinDays?: string;
  enteredSnfGreaterThan100?: string;
  enteredDateOfAccident?: string;
  eobBillLineMessageCount?: string;
  eobBillLineKey?: string;
  eobBillLineChAcctPartNum?: string;
  eobSrvAccum1?: string;
  eobSrvAccum2?: string;
  eobBenefitPeriodNum?: string;
  eobBenefitPeriodDay?: string;
  eobServiceCode?: string;
  eobTypeCode?: string;
  eobExceptionScreenInd?: string;
  enteredHospDays?: string;
  enteredHospCoins?: string;
  eobHospDays?: string;
  eobHospCoins?: string;
  enteredGreaterThan31DaysIndicator?: string;
  links?: { [key: string]: { [key: string]: string; }; };
}
