/**
 * fox-claims
 * Monolithic-style application containing generated components from legacy code modernization and custom developed APIs to support core claim processing.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {TRCDemoInfoVO} from './TRCDemoInfoVO';

export interface TRCObjectRequestVO {
  treasuryReconciliationId?: number;
  depositDetailId?: number;
  treasuryReconciliationCategory?: string;
  treasuryReconciliationStatus?: string;
  treasuryReconciliationAmount?: number;
  interestAmount?: number;
  priorYear?: boolean;
  reasonCode?: string;
  overpayment?: boolean;
  bulk?: boolean;
  backUpWithholding?: boolean;
  providerInsured?: string;
  businessUnit?: string;
  claimNumber?: number;
  memberNumber?: string;
  memberLastName?: string;
  memberFirstInit?: string;
  demographicInfo?: TRCDemoInfoVO;
}
