import {TRCDemoInfoVO} from './TRCDemoInfoVO';
/**
 * fox-claims
 * Monolithic-style application containing generated components from legacy code modernization and custom developed APIs to support core claim processing.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {TRCSystemConstantVO} from './TRCSystemConstantVO';
import {TreasuryReconciliationVO} from './TreasuryReconciliationVO';

export interface TreasuryReconciliationSystemsVO {
  treasuryReconciliation?: TreasuryReconciliationVO;
  additionalDetails?: TRCSystemConstantVO;
  demographicInfo?: TRCDemoInfoVO;
}
