import { AddressHoldAreaX } from './address-hold-area-x.model';
import { AddressHoldArea1 } from './address-hold-area1.model';
import { AddressHoldArea2 } from './address-hold-area2.model';
import { AuthorityReasons } from './authority-reasons.model';
import { BinaryFields } from './binary-fields.model';
import { ClaimDisplay } from './claim-display.model';
import { DateHoldAreaX } from './date-hold-area-x.model';
import { EcClaimNo } from './ec-claim-no.model';
import { ErrorFields } from './error-fields.model';
import { Filler22 } from './filler22.model';
import { Filler223 } from './filler223.model';
import { HoldAreaCompressedR } from './hold-area-compressed-r.model';
import { HoldAreaCompressedX } from './hold-area-compressed-x.model';
import { HoldAreaCompressed } from './hold-area-compressed.model';
import { InputHoldAreaX } from './input-hold-area-x.model';
import { InputHoldArea } from './input-hold-area.model';
import { NameHoldAreaR } from './name-hold-area-r.model';
import { NameHoldAreaX } from './name-hold-area-x.model';
import { NameHoldArea } from './name-hold-area.model';
import { OverrideKey } from './override-key.model';
import { ScreenHicNumber } from './screen-hic-number.model';
import { ScreenRrHic1 } from './screen-rr-hic1.model';
import { ScreenRrHic2 } from './screen-rr-hic2.model';
import { ScreenRrHic3 } from './screen-rr-hic3.model';
import { ScreenRrHic4 } from './screen-rr-hic4.model';
import { ScreenRrHic5 } from './screen-rr-hic5.model';
import { ScreenRrHic6 } from './screen-rr-hic6.model';
import { ScreeningField } from './screening-field.model';
import { StringNameOutX } from './string-name-out-x.model';
import { TitleWorkFields } from './title-work-fields.model';
import { TsName } from './ts-name.model';
import { WsHicNumberPositions } from './ws-hic-number-positions.model';
import { WsHoldCompressName } from './ws-hold-compress-name.model';
import { WsHoldInstName } from './ws-hold-inst-name.model';
import { WsHoldMakeInstNameR } from './ws-hold-make-inst-name-r.model';
import { WsHoldMakeInstName } from './ws-hold-make-inst-name.model';
import { WsParmDesc } from './ws-parm-desc.model';
import { Zip5digitWork } from './zip5digit-work.model';

/**
 * Model class WorkStorage
 * Path: screenbean/procclmaddrverf
 * Model: com::uhc::aarp::fox::domain::screenbean::procclmaddrverf::WorkStorage
 */
export class WorkStorage {
  commandEnteredInd = '';
  holdByte = '';
  holdCautionNumber = 0;
  wsCautionNumber = 0;
  cautionFound = '';
  nonbypassCautionReason = '';
  nonbypassStateReason = '';
  nonbypassPlanReason = '';
  nonbypassTosReason = '';
  nonbypassDosReason = '';
  nonbypassAcceptReason = '';
  cautionValued = '';
  stateValued = '';
  planValued = '';
  tosValued = '';
  dosValued = '';
  acceptValued = '';
  holdTitleValue = '';
  securitySub = 0;
  securitySub1 = 0;
  authSub = 0;
  msgCtnSub = 0;
  subPlan = 0;
  titleFoundInd = '';
  mbFound = '';
  duplicateFoundInd = '';
  rpdiskcvFoundInd = '';
  sendDependMsg1Ind = '';
  sendDependMsg2Ind = '';
  saveTitle = '';
  holdStateValue = '';
  stateFoundInd = '';
  saveState = '';
  changeInd = '';
  errorFields = new ErrorFields();
  errCnt = 0;
  screeningCheckInd = '';
  screenNameInd = 0;
  screeningField = new ScreeningField();
  specialCharacters = '';
  apostrophe = '';
  wsHoldInstName = new WsHoldInstName();
  wsHoldMakeInstName = new WsHoldMakeInstName();
  wsHoldMakeInstNameR = new WsHoldMakeInstNameR();
  stringNameOutR = '';
  stringNameOutX = new StringNameOutX();
  wsHoldCompressName = new WsHoldCompressName();
  charFound = '';
  inputHoldAreaX = new InputHoldAreaX();
  nameHoldAreaX = new NameHoldAreaX();
  addressHoldAreaX = new AddressHoldAreaX();
  dateHoldAreaX = new DateHoldAreaX();
  holdAreaCompressedX = new HoldAreaCompressedX();
  monthTable = '';
  currDateYmd = 0;
  wsLocation = 0;
  titleWorkFields = new TitleWorkFields();
  ascreeningField = '';
  monthWords: string[] = [];
  wsSite = 0;
  commaSub = 0;
  newSub = 0;
  sub = 0;
  sub1 = 0;
  sub2 = 0;
  sub3 = 0;
  sub4 = 0;
  sub5 = 0;
  sub6 = 0;
  sub7 = 0;
  sub8 = 0;
  sub9 = 0;
  sub10 = 0;
  sub11 = 0;
  sub12 = 0;
  psub = 0;
  tsub = 0;
  vsub = 0;
  rbaFld = 0;
  altaddJrlLen = 0;
  wsFilename = '';
  dateSub = 0;
  dateSub1 = 0;
  addr2Sub = 0;
  addr3Sub = 0;
  addressSub = 0;
  duplicateSub = 0;
  stateSub = 0;
  modCommLength = 0;
  ceTsqResponse = 0;
  ceTsqItem = 0;
  rpdiskcwRespCode = 0;
  wsRespCode = 0;
  ioErrorFname = '';
  notOpenFname = '';
  noSpaceFname = '';
  rceRtnCde = '';
  rceRtnMess = '';
  rceErrCond = '';
  wsDate = 0;
  wsParmDesc = new WsParmDesc();
  operatorKey = 0;
  overrideKey = new OverrideKey();
  zipWorkArea = '';
  zip5digitWork = new Zip5digitWork();
  inputHoldArea = new InputHoldArea();
  nameHoldArea = new NameHoldArea();
  nameHoldAreaR = new NameHoldAreaR();
  addressHoldArea1 = new AddressHoldArea1();
  addressHoldArea2 = new AddressHoldArea2();
  holdAreaCompressed = new HoldAreaCompressed();
  holdAreaCompressedR = new HoldAreaCompressedR();
  binaryFields = new BinaryFields();
  blankSw = '';
  inSub = 0;
  outSub = 0;
  workSub = 0;
  nameSub = 0;
  nameSub2 = 0;
  saveNameCompressed = '';
  saveAddrCompressed = '';
  saveCityCompressed = '';
  tsName = new TsName();
  tsItemNo = 0;
  claimDisplay = new ClaimDisplay();
  ecClaimNo = new EcClaimNo();
  gregorianDate = 0;
  julianDate = 0;
  dayTable = '';
  wsDate1 = 0;
  wsDate2 = 0;
  wsDescPos: string[] = [];
  saveNameCompressedR = '';
  saveAddrCompressedR = '';
  gregMm = 0;
  gregDd = 0;
  gregYy = 0;
  julYy = 0;
  julDdd = 0;
  tabDays: number[] = [];
  titleItem = new Filler22();
  stateItem = new Filler223();
  wsMcnUpdateInd = '';
  newMedIdInd = '';
  validMedIdInd = '';
  updateRpdiskcwInd = '';
  alphanumericInd = '';
  screenHicNumber = new ScreenHicNumber();
  wsHicNumberPositions = new WsHicNumberPositions();
  screenRrHic1 = new ScreenRrHic1();
  screenRrHic2 = new ScreenRrHic2();
  screenRrHic3 = new ScreenRrHic3();
  screenRrHic4 = new ScreenRrHic4();
  screenRrHic5 = new ScreenRrHic5();
  screenRrHic6 = new ScreenRrHic6();
  screenMbiDigits: string[] = [];
  screenMbiPos5 = '';
  screenMbiPos8 = '';
  screenMbiPos9 = '';
  screenMbiPos12 = '';
  authorityReasons = new AuthorityReasons();
}
