import { Rpdmb37 } from './rpdmb37.model';
import { AccessClmNumRecord } from './access-clm-num-record.model';
import { AutoGenerateClmLetter } from './auto-generate-clm-letter.model';
import { BlBillLine } from './bl-bill-line.model';
import { CicsGo05ErrorMsgLnkArea } from './cics-go05-error-msg-lnk-area.model';
import { ClaimEligibilityData } from './claim-eligibility-data.model';
import { ClaimEligibilityTsq } from './claim-eligibility-tsq.model';
import { ClaimNumberRecord } from './claim-number-record.model';
import { ClaimNumbers } from './claim-numbers.model';
import { CmnErrorRtneWrkStorArea } from './cmn-error-rtne-wrk-stor-area.model';
import { DialModInOutReturnCodes } from './dial-mod-in-out-return-codes.model';
import { DialModeCommLinkArea } from './dial-mode-comm-link-area.model';
import { LuwErrorMessageRecord } from './luw-error-message-record.model';
import { ScClaimNo } from './sc-claim-no.model';
import { TempStorQueueIOLnkArea } from './temp-stor-queue-iolnk-area.model';
import { TrnsfBusTempStorQueue } from './trnsf-bus-temp-stor-queue.model';
import { WsErisaInfo } from './ws-erisa-info.model';

/**
 * Model class WorkStorage
 * Path: screenbean/mendofclaim/beans
 * Model: com::uhc::aarp::fox::domain::screenbean::mendofclaim::beans::WorkStorage
 * Legacy Mapping: WS-FIELDS
 */
export class WorkStorage {
  wsMembershipNumber = 0;
  wsCcyy = 0;
  wsYear = 0;
  wsLeapYear = 0;
  wsClaimHold = 0;
  wsClaimNoYdddc = '';
  wsClaimNoLllsss = '';
  ecCarrierIonsid = 0;
  errorIn6o17Ind = '';
  tsqInErrorInd = '';
  prevEccStatusInd = '';
  pa2Ind = '';
  fileErrorInd = '';
  stopEverything = '';
  commandEnteredInd = '';
  foreignContryInd = '';
  rpdiskcyReadInd = '';
  respCode = 0;
  wsQueueItemno = 0;
  commandCommLen = 0;
  electClaimCommLen = 0;
  modCommLength = 0;
  rbaFld = 0;
  logKey = 0;
  sub = 0;
  sub3 = 0;
  sub450 = 0;
  sub845 = 0;
  esub = 0;
  psub = 0;
  peSub = 0;
  erSub = 0;
  lnpSub = 0;
  billSub = 0;
  itemSub = 0;
  lerPlSub = 0;
  cautionSub = 0;
  delayDaysCntr = 0;
  erisaFoundCount = 0;
  medsupPlanCount = 0;
  procClaimNoKey = 0;
  holdClaimNumber = 0;
  unpackIonsId = 0;
  holdErrorMessage = '';
  holdErisaEmployerId = '';
  holdErisaStartDate = '';
  holdErisaEndDate = '';
  saveErisaEmployerId = '';
  saveErisaStartDate = '';
  saveErisaEndDate = '';
  saveErisaPlanCode = '';
  erisaParaFoundInd = '';
  medsupPlanFound = '';
  erisaDatesInd = '';
  noErisaPlansInd = '';
  tosZOrY1Ind = '';
  electronicClaimInd = '';
  caution95LeReInd = '';
  caution45PpoInd = '';
  intervalTime = 0;
  wsTempLocations = 0;
  claimNoKey = 0;
  memberNoKey = 0;
  wsBuildMembNum = 0;
  wsBuildAssc = 0;
  wsBuildInsCode = 0;
  ioMsg = '';
  ioErrorDash = '';
  ioErrorCond = '';
  trnsfBusTempStorQueue = new TrnsfBusTempStorQueue();
  tempStorQueueIOLnkArea = new TempStorQueueIOLnkArea();
  luwModuleErrorPart = new LuwErrorMessageRecord();
  holdRtnMsg = '';
  ioErrorJournalRec2 = '';
  oiMembNo = '';
  oiAssoc = '';
  oiInsCode = '';
  oiClaimNo = '';
  oiTime = 0;
  oiDate = 0;
  oiTermId = '';
  oiIonsId = '';
  wsRpdtgo05 = new CicsGo05ErrorMsgLnkArea();
  wsLth = 0;
  wsResponseCode = 0;
  finishDi430 = '';
  finishDi821 = '';
  di82100Linkage = new AccessClmNumRecord();
  luwReturnFields = new DialModeCommLinkArea();
  dialModInOutReturnCodes = new DialModInOutReturnCodes();
  procClaimNoFile = new ClaimNumberRecord();
  wsSplitReminder = '';
  wsPpoSplitReminder = '';
  wsTsqWrongName = 0;
  wsDateOfTsq = 0;
  wsTsqOpId = '';
  wsTemModule = '';
  wsTemQueue = '';
  wsTemFunction = '';
  wsTemAccount = '';
  wsTemClaim = '';
  wsTsqName = '';
  cioCommand = '';
  cioSegment = '';
  cioRCode = '';
  cioRMsg = '';
  cioRCond = '';
  heModule = '';
  heName = '';
  heFunctionCode = '';
  heReturnCode = '';
  heReturnMessage = '';
  heExpFunctionCode = '';
  heExpReturnCode = '';
  wsDelayMsgStart = 0;
  wsDelayMsgFinish = 0;
  wsStatusField = '';
  claimEligibilityTsq = new ClaimEligibilityTsq();
  ceTsqItem = 0;
  ceTsqResponse = 0;
  ceTsqErrorInd = '';
  wsTermid = '';
  blTsqPrefx = '';
  blTsqTermid = '';
  blTsqEobScrn = '';
  blTsqSuffx = '';
  oiFunction = '';
  oiFunctionLb = '';
  oiRetCode = '';
  dateFuncPgm = '';
  wsJulianClaimNumber = '';
  wsJulianClaimYyyyddd9 = 0;
  wsClaimDateInteger = 0;
  wsComJulianDate = '';
  wsJulianCurdtYyyyddd = '';
  wsJulianCurdtYyyyddd9 = 0;
  wsCurrentDateInteger = 0;
  resultYear9 = 0;
  wsAgeOfClaim = 0;
  wsHoldDateNum = 0;
  wsHoldYear = '';
  wsPlanCode = '';
  wsCicsDate = '';
  wsKeyTimeStamp = 0;
  wsBillLineDate = 0;
  wsClaimServFromDate = 0;
  wsClaimServToDate = 0;
  wsErisaDates = 0;
  dcdatoffRetCode = '';
  dcdatoffReason = '';
  dcdatoffOutDate = '';
  dcdatoffInDate = '';
  dcdatoffInFormat = '';
  dcdatoffOutFormat = '';
  dcdatoffDayOffset = 0;
  dcdatwdyRetCode = '';
  dcdatwdyReason = '';
  dcdatwdyWeekdayInd = '';
  dcdatwdyInDate = '';
  dcdatwdyInFormat = '';
  dcdatwdyOutputInd = '';
  wsErisaInfos: WsErisaInfo[] = [];
  cmnErrorRtneWrkStorArea = new CmnErrorRtneWrkStorArea();
  wsBillLineTable: BlBillLine[] = [];
  wsBillLineItem = new BlBillLine();
  wsErisaClaimNumber = 0;
  wsRpd05o80WorkArea = new AutoGenerateClmLetter();
  mapCommandLine = '';
  claimNumbers: ClaimNumbers[] = [];
  reminderMessage1A = '';
  reminderMessage1 = '';
  reminderMessage2A = '';
  reminderMessage2 = '';
  paysCtrA = '';
  paysCtr = 0;
  qualityCtrA = '';
  qualityCtr = 0;
  noPayCtrA = '';
  noPayCtr = 0;
  suspendedCtrA = '';
  suspendedCtr = 0;
  errLineA = '';
  errLine = '';
  scClaimNo = new ScClaimNo();
  Rpdmb37 = new Rpdmb37();
  electronicClaim = '';
  errorIn6o17 = '';
  erisaParaFound = '';
  tsqInError = '';
  erisaDatesNo = '';
  erisaDatesYes = '';
  erisaParaNotFound = '';
  tosZOrY = '';
  caution45PpoFound = '';
  cehQueuePrefix = '';
  cehHhAccountNumber = 0;
  cehEibtaskn = 0;
  claimEligibilityData = new ClaimEligibilityData();
  ceiPrimaryItem = '';
  ceItemCnt = 0;
  ceiSpouseItem = '';
  ceiPrevSpItem = '';
  cehPid1InsuredCode = '';
  cehSid1InsuredCode = '';
  cehPsd1InsuredCode = '';
  ceiHouseholdItem = '';
  ceiHeaderItem = '';
}
