import {AddressTsqRecord, HospBenLnTSQ, OopConstant} from '@fox/shared';
import {ClaimEligibilityTsQueue} from '../../process-end-of-claim/model/claim-eligibility-ts-queue.model';
// import { LnkWrkStorageIcdCdDescRecord } from '../rtrvicd/lnk-wrk-storage-icd-cd-desc-record.model';
import {BeneExtError} from './bene-ext-error.model';
import {BillTable1} from './bill-table1.model';
import {BillTable2} from './bill-table2.model';
import {BillTable3} from './bill-table3.model';
import {CautionBenMax} from './caution-ben-max.model';
import {CautionProvNotAccept} from './caution-prov-not-accept.model';
import {Caution76Line} from './caution76-line.model';
import {ClaimHistoryTimeLineTable} from './claim-history-time-line-table.model';
import {ConsistLtrDaysError1} from './consist-ltr-days-error1.model';
import {ConsistLtrDaysError2} from './consist-ltr-days-error2.model';
import {ConsistMedDaysError} from './consist-med-days-error.model';
import {DupOutpatMessage} from './dup-outpat-message.model';
import {ErrorLine} from './error-line.model';
import {HclChargeLn} from './hcl-charge-ln.model';
import {HoldFields} from './hold-fields.model';
import {HoldQaRecord} from './hold-qa-record.model';
import {IcuMessage} from './icu-message.model';
import {MedDaysError} from './med-days-error.model';
import {MentalIllnessCaution} from './mental-illness-caution.model';
import {NonLtrMaxError} from './non-ltr-max-error.model';
import {ProgramError} from './program-error.model';
import {ProviderAddr2NpiLine} from './provider-addr2-npi-line.model';
import {ProviderLine1} from './provider-line1.model';
import {ProviderLine2} from './provider-line2.model';
import {ProviderLine3} from './provider-line3.model';
import {ProviderLine4} from './provider-line4.model';
import {SaveBillLines2} from './save-bill-lines2.model';
import {StateAaMsg} from './state-aa-msg.model';
import {StateMsg} from './state-msg.model';
import {WarningsAndCautions} from './warnings-and-cautions.model';
import {WsBillsArea} from './ws-bills-area.model';
import {WsBlhItem} from './ws-blh-item.model';
import {WsCicsWorkArea} from './ws-cics-work-area.model';
import {WsEMVariableTable} from './ws-emvariable-table.model';
import {WsHospBenefitData} from './ws-hosp-benefit-data.model';
import {WsHospChargeData} from './ws-hosp-charge-data.model';
import {WsIcdCodePo} from './ws-icd-code-po.model';
import {WsIndicatorsArea} from './ws-indicators-area.model';
import {WsLegalEntityReFields} from './ws-legal-entity-re-fields.model';
import {WsPlanCodeTable} from './ws-plan-code-table.model';
import {WsPpMsgVarTable} from './ws-pp-msg-var-table.model';
import {WsPtifKey} from './ws-ptif-key.model';

/**
 * Model class WorkStorage
 * Path: screenbean/procclmhospchrg
 * Model: com::uhc::aarp::fox::domain::screenbean::procclmhospchrg::WorkStorage
 * Legacy Mapping: WORK-FILE-AREA
 */
export class WorkStorage {
  holdPtifRecord = '';
  holdQaRecord = new HoldQaRecord();
  wsPtifKey = new WsPtifKey();
  wsPlanType = '';
  wsMcAmt = 0;
  wsMcRem = 0;
  wsSub = 0;
  mcKeyType = 0;
  mcKeyDate = 0;
  wsHospPerInd = '';
  wsHospPerAmt = 0;
  primeClaimNo9 = 0;
  oopTsItem = 0;
  wsOopDate = '';
  wsOopYear = 0;
  wsOopSplitYy = 0;
  wsOopPercentage = 0;
  wsOopMaxAmount = 0;
  wsOopMsgNumber = 0;
  wsOopBenefitSave = 0;
  wsOopAccumAmount = 0;
  wsOopDifference = 0;
  wsOopComputed = 0;
  wsOopApplied = 0;
  wsOopPlanInd = '';
  wsOopTosInd = '';
  oopTsqInd = '';
  wsOopDb2Ind = '';
  wsOopOpfcInd = '';
  wsOopTsqHaInd = '';
  oopSub = 0;
  oopHaSub = 0;
  mc3Sub = 0;
  wsMcResp = 0;
  wsQcResp = 0;
  wsOopMcPlan = '';
  wsOopMcInd = '';
  wsOopKeyYear = 0;
  wsOopKeyPlan = '';
  wsOopKeyDate = 0;
  wsOopPckYear = 0;
  wsOopPckPlan = '';
  wsOopPckDate = 0;
  wsMsgVariableIndFlag = '';
  wsPpMsgVarTable = new WsPpMsgVarTable();
  mvRemarkCode = 0;
  wsEMVariableTable = new WsEMVariableTable();
  msgSub = 0;
  dup1Sub = 0;
  msgNum = 0;
  varSub = 0;
  wsMsgVarCnt = 0;
  charCnt = 0;
  addClaimMsgInd = '';
  messageFoundInd = '';
  wsMsgNumber = 0;
  wsMsgPlanCd = '';
  wsMsgCcyy = 0;
  wsMsgAmountEdited = '';
  wsMsgNumberEdited = 0;
  ihdWaiverMsg = 0;
  wsMsgDays = 0;
  wsMsgVisits = 0;
  wsMsgClaim = 0;
  wsMsgAmountField = 0;
  wsMapAmountField = 0;
  mvPlanCode = '';
  mvPlanLtcDays = '';
  mvBlDosCcyy = '';
  mvPlanYtdVisits = '';
  mvPlanYtdDedAmt = '';
  mvClDosCcyy = '';
  mvClTotDedAmt = '';
  mvPlanMaxDedAmt = '';
  mvBlOopAmt = '';
  mvPlanOopYtdAmt = '';
  mvPlanOopCalMax = '';
  mvBlTripDedAmt = '';
  mvClaimNumber = '';
  mvPlanMaxVisits = '';
  wsTypeOfStay = '';
  wsBlhItems: WsBlhItem[] = [];
  blhIndex = 0;
  wsBlhTableMax = 0;
  wsBlhMaxOffset = 0;
  wsBlhStartDate = 0;
  wsBlhEndDate = 0;
  wsBlhCurrFrom = 0;
  wsBlhCurrTo = 0;
  wsBlhHistFrom = 0;
  wsBlhHistTo = 0;
  wsBlhPosOffset = 0;
  wsBlhOffset = 0;
  wsBlhH2BenPerPos = 0;
  wsBlhPriorH2Cnt = 0;
  wsBlhFutureH2Cnt = 0;
  wsBlhGapCounter = 0;
  wsBlhH4Counter = 0;
  wsBlhCcyymmdd = '';
  wsBlhH2Ind = '';
  wsBlhH4Ind = '';
  wsBlhQ0Ind = '';
  wsIcdCodePo = new WsIcdCodePo();
  wsIcdMapField1 = '';
  wsIcdMapField2 = '';
  wsIcdMapField3 = '';
  wsIcdCheckIndicatorFlag = '';
  wsIcdCicsExepIndFlag = '';
  icdCodeValueInd = '';
  icdCodeErrorInd = '';
  icdCodeError2Ind = '';
  wsReadNotfnd = '';
  claimHistoryTimeLineTable = new ClaimHistoryTimeLineTable();
  chtlBillCtr = 0;
  gapCheck = 0;
  claimSfdInteger = 0;
  claimStdInteger = 0;
  currentSfdInteger = 0;
  currentStdInteger = 0;
  snfCurSfd = 0;
  snfCurStd = 0;
  tlFirstBillLine = 0;
  timeLineDate = '';
  snfDayCounter = 0;
  tlSub = '';
  tlSub1 = 0;
  tlSub2 = 0;
  tlSub3 = 0;
  tlSfd = 0;
  tlStd = 0;
  snfStatusLetterInd = '';
  chtlCompletedInd = '';
  snfService = '';
  snfType = '';
  screenDate = '';
  screenDate2 = '';
  workDate = '';
  wsDosFromCcyymmdd = '';
  wsDosToCcyymmdd = '';
  workOutpatDateYmd = '';
  workDate2 = '';
  saveSerDate = '';
  saveSerFromYmd = '';
  saveEcsFromYmd = '';
  saveEcsToYmd = '';
  saveSerToYmd = '';
  wsFromDateYmd = '';
  wsToDateYmd = '';
  sfdJul = '';
  stdJul = '';
  ifdJul = '';
  itdJul = '';
  tosSerFromYmd = '';
  tosSerToYmd = '';
  saveIcuDate = '';
  saveIcuFromYmd = '';
  saveIcuToYmd = '';
  saveDateOfSurgeryYmd = '';
  saveTermDate = '';
  saveEffDate = '';
  holdFyy = 0;
  holdTyy = 0;
  holdSpan = 0;
  wsPedYmd = 0;
  earliestEffDate = 0;
  latestTermDate = 0;
  rrStartDate = 0;
  wsFileDate = '';
  wsFileSfd = 0;
  wsFileStd = 0;
  wsFilePed = 0;
  incDateYmd = 0;
  msFromDate = 0;
  msToDate = 0;
  saveFrom = 0;
  saveDate = 0;
  saveDate1 = 0;
  tempDate = 0;
  holdDate = 0;
  saveStartBpDate = 0;
  saveEndBpDate = 0;
  incurralDate = 0;
  actuarialIncurralDate = 0;
  riderIncDate = 0;
  riderServDate = 0;
  riderIncDateYmd = 0;
  riderServDateYmd = 0;
  riderEffDateYmd = 0;
  riderTermDateYmd = 0;
  benStartDate = 0;
  benStMmdd = '';
  benEndDate = 0;
  julSrfDate = 0;
  julBenStartDate = 0;
  earliestSnfDate = 0;
  startCovPlus3 = 0;
  unpkFromDate = 0;
  unpkToDate = 0;
  julFromDate = 0;
  julToDate = 0;
  julMsgTestDate = 0;
  holdHospToDate = 0;
  julLagFromDate = 0;
  julLagToDate = 0;
  julHospFromDate = 0;
  julHospToDate = 0;
  julLagTosFromDate = 0;
  julLagTosToDate = 0;
  lagChgFromDate = '';
  lagChgToDate = '';
  lagConfToDate = '';
  lagConfFromDate = '';
  wsServiceFromDate = '';
  wsServiceToDate = '';
  wsPlnExtTermYymmdd = '';
  wsPlnEffectiveYymmdd = '';
  wsUnpackYymmdd = '';
  wsDoaYymmdd = '';
  wsDoaYyddd = '';
  wsDoaYyddd1 = '';
  wsHoldBenStartDate = '';
  julDate = '';
  gregDate = '';
  addrServDate = '';
  unpackRiderEffDate = '';
  unpackStartDate = '';
  unpackStopDate = '';
  workPedYmd = '';
  whClmServToYmd = '';
  wkYmd = '';
  hospFromDate = '';
  hospToDate = '';
  confFromDate = '';
  confToDate = '';
  wsGregDate = '';
  wsJulDate = '';
  daysToSubtract = 0;
  signedJulDays = 0;
  subYear = 0;
  subMonth = 0;
  wsVndatePgm = '';
  wsFuncName = '';
  wsDcReturnCode = '';
  wsDcReasonCode = '';
  wsResultField = 0;
  wsDateField1 = '';
  wsInFormat1 = '';
  wsDateField2 = '';
  wsInFormat2 = '';
  vndatePgm = '';
  incurralEnd = '';
  hospIsAcceptable = '';
  surgIsEligible = '';
  dupFoundInd1 = '';
  dupFoundInd2 = '';
  icuFlag1 = '';
  h2Dup = '';
  planCAgeChangeInd = '';
  relatedHistory = '';
  sendCaution = '';
  line1Ind = '';
  surgeryDaysPaid = 0;
  saveBenPerPos = 0;
  wsBenPerPos = 0;
  wsBenPerLifeAggr = 0;
  wsAggMaxAmt = 0;
  hold50VisitAggrYr = 0;
  holdNewhipPlanH1Aggr = 0;
  aggrMetMsg = 0;
  startBenPerPos = 0;
  benPerPos = 0;
  saveRelResponse = '';
  benefitPeriodPlanInd = '';
  unpackedBenPerNo = 0;
  noOfDays = 0;
  benSub = 0;
  savePreExistPlan = '';
  dateHold = 0;
  yearSub = 0;
  wsAmt1 = 0;
  wsAmt2 = 0;
  splitInd = '';
  sendWarning = '';
  confinementLagInd = '';
  foundLastConf = '';
  perf4705Sw = '';
  snfPeriodInd = '';
  snfNopayInd = '';
  snfSpanInd = '';
  hbSnfInd = '';
  possOthrType = '';
  hospFoundInd = '';
  postHospFoundInd = '';
  snfFoundInd = '';
  ltrOptionInd = '';
  nopayWarningInd = '';
  riderCautionInd = '';
  sentMessageX = '';
  sentMessageN = 0;
  hospPlan = '';
  confPlanCode = '';
  newhipSurgeryDate = 0;
  funcName = '';
  dcReturnCode = '';
  dcReasonCode = '';
  resultField = '';
  dateField1 = '';
  inFormat = '';
  outFormat = '';
  dayOffset = 0;
  snfBenefit = 0;
  confinePos = 0;
  confWaitPos = 0;
  benWaitPos = 0;
  confineAmt = 0;
  sub = 0;
  sub1 = 0;
  sub2 = 0;
  sub3 = 0;
  sub4 = 0;
  sub5 = 0;
  sub7 = 0;
  sub9 = 0;
  sub10 = 0;
  sub11 = 0;
  billLine = 0;
  hldBillLine = 0;
  subDup = 0;
  pointerSub = 0;
  planSub = 0;
  planSubHold = 0;
  exclPlanSub = 0;
  planSub2 = 0;
  planSub3 = 0;
  planSub4 = 0;
  riderPointer = 0;
  riderSub = 0;
  relHospSub = 0;
  tosSub = 0;
  mcSub = 0;
  mcSplitSub = 0;
  sp1McSub = 0;
  sp2McSub = 0;
  hosSub = 0;
  snfSub = 0;
  snfSub2 = 0;
  holdSnfSub2 = 0;
  ltrSub = 0;
  addrHistSub = 0;
  scSub = 0;
  scSub2 = 0;
  stSub1 = 0;
  stSub2 = 0;
  stSub3 = 0;
  sortCtr1 = 0;
  sortCtr2 = 0;
  s1 = 0;
  s2 = 0;
  screenSub = 0;
  deductSub = 0;
  holdSub = 0;
  hold2Sub = 0;
  chargeSub = 0;
  startSub = 0;
  endSub = 0;
  securitySub = 0;
  saveFirstSub = 0;
  saveLastSub = 0;
  unSub = 0;
  saveLtrSubs: number[] = [];
  saveHMaxSubs: number[] = [];
  ptifSub = 0;
  hptifSub = 0;
  splitSub = 0;
  hsub = 0;
  s1407 = 0;
  s1408 = 0;
  lerPlSub = 0;
  lerDtSub = 0;
  hiphapSub = 0;
  itemSub = 0;
  ppSub = 0;
  ptifRecordCtr = 0;
  planTosRecordCtr = 0;
  mcRecordCtr = 0;
  chargeBillLineCtr = 0;
  benefitBillLineCtr = 0;
  wsIndicators = new WsIndicatorsArea();
  holdFields = new HoldFields();
  billTableHold = '';
  billHistSubs: number[] = [];
  latestBenHdg1 = '';
  latestBenHdg1a = '';
  latestBenHdg2 = '';
  latestBenHdg2a = '';
  possibleRelHdg1 = '';
  possibleRelHdg2 = '';
  providerLine1 = new ProviderLine1();
  providerLine2 = new ProviderLine2();
  providerLine3 = new ProviderLine3();
  providerLine4 = new ProviderLine4();
  providerAddr2NpiLine = new ProviderAddr2NpiLine();
  errorLine = new ErrorLine();
  waringsAndCautions = new WarningsAndCautions();
  consistChargeErr = '';
  caution76Line = new Caution76Line();
  cautionBenMax = new CautionBenMax();
  dupOutpatMessage = new DupOutpatMessage();
  beneExtErr = new BeneExtError();
  cautionProvNotAccept = new CautionProvNotAccept();
  medDaysError = new MedDaysError();
  consistMedDaysError = new ConsistMedDaysError();
  consistLtrDaysErr1 = new ConsistLtrDaysError1();
  consistLtrDaysErr2 = new ConsistLtrDaysError2();
  stateMsg = new StateMsg();
  stateAaMsg = new StateAaMsg();
  icuMessage = new IcuMessage();
  mentalIlinessCaution = new MentalIllnessCaution();
  programError = new ProgramError();
  nonLtrMaxError = new NonLtrMaxError();
  tableMaxError = '';
  oop2ManyYrsError = '';
  oopBlMaxError = '';
  wsLegalEntityReFields = new WsLegalEntityReFields();
  wsCicsWorkArea = new WsCicsWorkArea();
  preStandardPlanInd = '';
  billTable1 = new BillTable1();
  billTable2 = new BillTable2();
  billTable3 = new BillTable3();
  snfTos = '';
  wsChkRecNbr = 0;
  tsSub = 0;
  wsPlanCodeTable = new WsPlanCodeTable();
  wsAggr = 0;
  combAggrAmt = 0;
  wsMsgVariable = '';
  oopConstant = new OopConstant();
  dhdiTosh5planInd = '';
  holdBenPerDaysForRiders: number[] = [];
  // ptifAggregateMaxFieldsList: PtifAggregateMaxFieldsPO[] = [];
  // PtifDeductibleFieldsList: PtifDeductibleFieldsPO[] = [];
  saveBillLine2 = new SaveBillLines2();
  wsHospChargeLineData = new WsHospChargeData();
  cedEligibilityIoArea = new ClaimEligibilityTsQueue();
  wsHospBenefitTsq = new HospBenLnTSQ();
  // linkIcdData = new LnkWrkStorageIcdCdDescRecord();
  //  planTosInfoList: PlanTosInfoRecordPO[] = [];
  claimHisTimeLineTbl = new ClaimHistoryTimeLineTable();
  hclChargeLine = new HclChargeLn();
  wsHospBenefitData = new WsHospBenefitData();
  addressTsq = new AddressTsqRecord();
  billArea = new WsBillsArea();

}
